// File generated by the BNF Converter (bnfc 2.9.4.1).

package stella;
/** Composition Visitor
*/

public class ComposVisitor<A> implements
  stella.Absyn.Program.Visitor<stella.Absyn.Program,A>,
  stella.Absyn.LanguageDecl.Visitor<stella.Absyn.LanguageDecl,A>,
  stella.Absyn.Extension.Visitor<stella.Absyn.Extension,A>,
  stella.Absyn.Decl.Visitor<stella.Absyn.Decl,A>,
  stella.Absyn.LocalDecl.Visitor<stella.Absyn.LocalDecl,A>,
  stella.Absyn.Annotation.Visitor<stella.Absyn.Annotation,A>,
  stella.Absyn.ParamDecl.Visitor<stella.Absyn.ParamDecl,A>,
  stella.Absyn.ReturnType.Visitor<stella.Absyn.ReturnType,A>,
  stella.Absyn.ThrowType.Visitor<stella.Absyn.ThrowType,A>,
  stella.Absyn.Expr.Visitor<stella.Absyn.Expr,A>,
  stella.Absyn.MatchCase.Visitor<stella.Absyn.MatchCase,A>,
  stella.Absyn.OptionalTyping.Visitor<stella.Absyn.OptionalTyping,A>,
  stella.Absyn.PatternData.Visitor<stella.Absyn.PatternData,A>,
  stella.Absyn.ExprData.Visitor<stella.Absyn.ExprData,A>,
  stella.Absyn.Pattern.Visitor<stella.Absyn.Pattern,A>,
  stella.Absyn.LabelledPattern.Visitor<stella.Absyn.LabelledPattern,A>,
  stella.Absyn.Binding.Visitor<stella.Absyn.Binding,A>,
  stella.Absyn.Type.Visitor<stella.Absyn.Type,A>,
  stella.Absyn.VariantFieldType.Visitor<stella.Absyn.VariantFieldType,A>,
  stella.Absyn.RecordFieldType.Visitor<stella.Absyn.RecordFieldType,A>,
  stella.Absyn.Typing.Visitor<stella.Absyn.Typing,A>
{
    /* Program */
    public stella.Absyn.Program visit(stella.Absyn.AProgram p, A arg)
    {
      stella.Absyn.LanguageDecl languagedecl_ = p.languagedecl_.accept(this, arg);
      stella.Absyn.ListExtension listextension_ = new stella.Absyn.ListExtension();
      for (stella.Absyn.Extension x : p.listextension_)
      {
        listextension_.add(x.accept(this,arg));
      }
      stella.Absyn.ListDecl listdecl_ = new stella.Absyn.ListDecl();
      for (stella.Absyn.Decl x : p.listdecl_)
      {
        listdecl_.add(x.accept(this,arg));
      }
      return new stella.Absyn.AProgram(languagedecl_, listextension_, listdecl_);
    }

    /* LanguageDecl */
    public stella.Absyn.LanguageDecl visit(stella.Absyn.LanguageCore p, A arg)
    {
      return new stella.Absyn.LanguageCore();
    }

    /* Extension */
    public stella.Absyn.Extension visit(stella.Absyn.AnExtension p, A arg)
    {
      stella.Absyn.ListExtensionName listextensionname_ = p.listextensionname_;
      return new stella.Absyn.AnExtension(listextensionname_);
    }

    /* Decl */
    public stella.Absyn.Decl visit(stella.Absyn.DeclFun p, A arg)
    {
      stella.Absyn.ListAnnotation listannotation_ = new stella.Absyn.ListAnnotation();
      for (stella.Absyn.Annotation x : p.listannotation_)
      {
        listannotation_.add(x.accept(this,arg));
      }
      String stellaident_ = p.stellaident_;
      stella.Absyn.ListParamDecl listparamdecl_ = new stella.Absyn.ListParamDecl();
      for (stella.Absyn.ParamDecl x : p.listparamdecl_)
      {
        listparamdecl_.add(x.accept(this,arg));
      }
      stella.Absyn.ReturnType returntype_ = p.returntype_.accept(this, arg);
      stella.Absyn.ThrowType throwtype_ = p.throwtype_.accept(this, arg);
      stella.Absyn.ListDecl listdecl_ = new stella.Absyn.ListDecl();
      for (stella.Absyn.Decl x : p.listdecl_)
      {
        listdecl_.add(x.accept(this,arg));
      }
      stella.Absyn.Expr expr_ = p.expr_.accept(this, arg);
      return new stella.Absyn.DeclFun(listannotation_, stellaident_, listparamdecl_, returntype_, throwtype_, listdecl_, expr_);
    }
    public stella.Absyn.Decl visit(stella.Absyn.DeclTypeAlias p, A arg)
    {
      String stellaident_ = p.stellaident_;
      stella.Absyn.Type type_ = p.type_.accept(this, arg);
      return new stella.Absyn.DeclTypeAlias(stellaident_, type_);
    }

    /* LocalDecl */
    public stella.Absyn.LocalDecl visit(stella.Absyn.ALocalDecl p, A arg)
    {
      stella.Absyn.Decl decl_ = p.decl_.accept(this, arg);
      return new stella.Absyn.ALocalDecl(decl_);
    }

    /* Annotation */
    public stella.Absyn.Annotation visit(stella.Absyn.InlineAnnotation p, A arg)
    {
      return new stella.Absyn.InlineAnnotation();
    }

    /* ParamDecl */
    public stella.Absyn.ParamDecl visit(stella.Absyn.AParamDecl p, A arg)
    {
      String stellaident_ = p.stellaident_;
      stella.Absyn.Type type_ = p.type_.accept(this, arg);
      return new stella.Absyn.AParamDecl(stellaident_, type_);
    }

    /* ReturnType */
    public stella.Absyn.ReturnType visit(stella.Absyn.NoReturnType p, A arg)
    {
      return new stella.Absyn.NoReturnType();
    }
    public stella.Absyn.ReturnType visit(stella.Absyn.SomeReturnType p, A arg)
    {
      stella.Absyn.Type type_ = p.type_.accept(this, arg);
      return new stella.Absyn.SomeReturnType(type_);
    }

    /* ThrowType */
    public stella.Absyn.ThrowType visit(stella.Absyn.NoThrowType p, A arg)
    {
      return new stella.Absyn.NoThrowType();
    }
    public stella.Absyn.ThrowType visit(stella.Absyn.SomeThrowType p, A arg)
    {
      stella.Absyn.ListType listtype_ = new stella.Absyn.ListType();
      for (stella.Absyn.Type x : p.listtype_)
      {
        listtype_.add(x.accept(this,arg));
      }
      return new stella.Absyn.SomeThrowType(listtype_);
    }

    /* Expr */
    public stella.Absyn.Expr visit(stella.Absyn.If p, A arg)
    {
      stella.Absyn.Expr expr_1 = p.expr_1.accept(this, arg);
      stella.Absyn.Expr expr_2 = p.expr_2.accept(this, arg);
      stella.Absyn.Expr expr_3 = p.expr_3.accept(this, arg);
      return new stella.Absyn.If(expr_1, expr_2, expr_3);
    }
    public stella.Absyn.Expr visit(stella.Absyn.Let p, A arg)
    {
      String stellaident_ = p.stellaident_;
      stella.Absyn.Expr expr_1 = p.expr_1.accept(this, arg);
      stella.Absyn.Expr expr_2 = p.expr_2.accept(this, arg);
      return new stella.Absyn.Let(stellaident_, expr_1, expr_2);
    }
    public stella.Absyn.Expr visit(stella.Absyn.LessThan p, A arg)
    {
      stella.Absyn.Expr expr_1 = p.expr_1.accept(this, arg);
      stella.Absyn.Expr expr_2 = p.expr_2.accept(this, arg);
      return new stella.Absyn.LessThan(expr_1, expr_2);
    }
    public stella.Absyn.Expr visit(stella.Absyn.LessThanOrEqual p, A arg)
    {
      stella.Absyn.Expr expr_1 = p.expr_1.accept(this, arg);
      stella.Absyn.Expr expr_2 = p.expr_2.accept(this, arg);
      return new stella.Absyn.LessThanOrEqual(expr_1, expr_2);
    }
    public stella.Absyn.Expr visit(stella.Absyn.GreaterThan p, A arg)
    {
      stella.Absyn.Expr expr_1 = p.expr_1.accept(this, arg);
      stella.Absyn.Expr expr_2 = p.expr_2.accept(this, arg);
      return new stella.Absyn.GreaterThan(expr_1, expr_2);
    }
    public stella.Absyn.Expr visit(stella.Absyn.GreaterThanOrEqual p, A arg)
    {
      stella.Absyn.Expr expr_1 = p.expr_1.accept(this, arg);
      stella.Absyn.Expr expr_2 = p.expr_2.accept(this, arg);
      return new stella.Absyn.GreaterThanOrEqual(expr_1, expr_2);
    }
    public stella.Absyn.Expr visit(stella.Absyn.Equal p, A arg)
    {
      stella.Absyn.Expr expr_1 = p.expr_1.accept(this, arg);
      stella.Absyn.Expr expr_2 = p.expr_2.accept(this, arg);
      return new stella.Absyn.Equal(expr_1, expr_2);
    }
    public stella.Absyn.Expr visit(stella.Absyn.NotEqual p, A arg)
    {
      stella.Absyn.Expr expr_1 = p.expr_1.accept(this, arg);
      stella.Absyn.Expr expr_2 = p.expr_2.accept(this, arg);
      return new stella.Absyn.NotEqual(expr_1, expr_2);
    }
    public stella.Absyn.Expr visit(stella.Absyn.TypeAsc p, A arg)
    {
      stella.Absyn.Expr expr_ = p.expr_.accept(this, arg);
      stella.Absyn.Type type_ = p.type_.accept(this, arg);
      return new stella.Absyn.TypeAsc(expr_, type_);
    }
    public stella.Absyn.Expr visit(stella.Absyn.Abstraction p, A arg)
    {
      stella.Absyn.ListParamDecl listparamdecl_ = new stella.Absyn.ListParamDecl();
      for (stella.Absyn.ParamDecl x : p.listparamdecl_)
      {
        listparamdecl_.add(x.accept(this,arg));
      }
      stella.Absyn.Expr expr_ = p.expr_.accept(this, arg);
      return new stella.Absyn.Abstraction(listparamdecl_, expr_);
    }
    public stella.Absyn.Expr visit(stella.Absyn.Tuple p, A arg)
    {
      stella.Absyn.ListExpr listexpr_ = new stella.Absyn.ListExpr();
      for (stella.Absyn.Expr x : p.listexpr_)
      {
        listexpr_.add(x.accept(this,arg));
      }
      return new stella.Absyn.Tuple(listexpr_);
    }
    public stella.Absyn.Expr visit(stella.Absyn.Record p, A arg)
    {
      stella.Absyn.ListBinding listbinding_ = new stella.Absyn.ListBinding();
      for (stella.Absyn.Binding x : p.listbinding_)
      {
        listbinding_.add(x.accept(this,arg));
      }
      return new stella.Absyn.Record(listbinding_);
    }
    public stella.Absyn.Expr visit(stella.Absyn.Variant p, A arg)
    {
      String stellaident_ = p.stellaident_;
      stella.Absyn.ExprData exprdata_ = p.exprdata_.accept(this, arg);
      return new stella.Absyn.Variant(stellaident_, exprdata_);
    }
    public stella.Absyn.Expr visit(stella.Absyn.Match p, A arg)
    {
      stella.Absyn.Expr expr_ = p.expr_.accept(this, arg);
      stella.Absyn.ListMatchCase listmatchcase_ = new stella.Absyn.ListMatchCase();
      for (stella.Absyn.MatchCase x : p.listmatchcase_)
      {
        listmatchcase_.add(x.accept(this,arg));
      }
      return new stella.Absyn.Match(expr_, listmatchcase_);
    }
    public stella.Absyn.Expr visit(stella.Absyn.List p, A arg)
    {
      stella.Absyn.ListExpr listexpr_ = new stella.Absyn.ListExpr();
      for (stella.Absyn.Expr x : p.listexpr_)
      {
        listexpr_.add(x.accept(this,arg));
      }
      return new stella.Absyn.List(listexpr_);
    }
    public stella.Absyn.Expr visit(stella.Absyn.Add p, A arg)
    {
      stella.Absyn.Expr expr_1 = p.expr_1.accept(this, arg);
      stella.Absyn.Expr expr_2 = p.expr_2.accept(this, arg);
      return new stella.Absyn.Add(expr_1, expr_2);
    }
    public stella.Absyn.Expr visit(stella.Absyn.LogicOr p, A arg)
    {
      stella.Absyn.Expr expr_1 = p.expr_1.accept(this, arg);
      stella.Absyn.Expr expr_2 = p.expr_2.accept(this, arg);
      return new stella.Absyn.LogicOr(expr_1, expr_2);
    }
    public stella.Absyn.Expr visit(stella.Absyn.Multiply p, A arg)
    {
      stella.Absyn.Expr expr_1 = p.expr_1.accept(this, arg);
      stella.Absyn.Expr expr_2 = p.expr_2.accept(this, arg);
      return new stella.Absyn.Multiply(expr_1, expr_2);
    }
    public stella.Absyn.Expr visit(stella.Absyn.LogicAnd p, A arg)
    {
      stella.Absyn.Expr expr_1 = p.expr_1.accept(this, arg);
      stella.Absyn.Expr expr_2 = p.expr_2.accept(this, arg);
      return new stella.Absyn.LogicAnd(expr_1, expr_2);
    }
    public stella.Absyn.Expr visit(stella.Absyn.Application p, A arg)
    {
      stella.Absyn.Expr expr_ = p.expr_.accept(this, arg);
      stella.Absyn.ListExpr listexpr_ = new stella.Absyn.ListExpr();
      for (stella.Absyn.Expr x : p.listexpr_)
      {
        listexpr_.add(x.accept(this,arg));
      }
      return new stella.Absyn.Application(expr_, listexpr_);
    }
    public stella.Absyn.Expr visit(stella.Absyn.ConsList p, A arg)
    {
      stella.Absyn.Expr expr_1 = p.expr_1.accept(this, arg);
      stella.Absyn.Expr expr_2 = p.expr_2.accept(this, arg);
      return new stella.Absyn.ConsList(expr_1, expr_2);
    }
    public stella.Absyn.Expr visit(stella.Absyn.Head p, A arg)
    {
      stella.Absyn.Expr expr_ = p.expr_.accept(this, arg);
      return new stella.Absyn.Head(expr_);
    }
    public stella.Absyn.Expr visit(stella.Absyn.IsEmpty p, A arg)
    {
      stella.Absyn.Expr expr_ = p.expr_.accept(this, arg);
      return new stella.Absyn.IsEmpty(expr_);
    }
    public stella.Absyn.Expr visit(stella.Absyn.Tail p, A arg)
    {
      stella.Absyn.Expr expr_ = p.expr_.accept(this, arg);
      return new stella.Absyn.Tail(expr_);
    }
    public stella.Absyn.Expr visit(stella.Absyn.Succ p, A arg)
    {
      stella.Absyn.Expr expr_ = p.expr_.accept(this, arg);
      return new stella.Absyn.Succ(expr_);
    }
    public stella.Absyn.Expr visit(stella.Absyn.LogicNot p, A arg)
    {
      stella.Absyn.Expr expr_ = p.expr_.accept(this, arg);
      return new stella.Absyn.LogicNot(expr_);
    }
    public stella.Absyn.Expr visit(stella.Absyn.Pred p, A arg)
    {
      stella.Absyn.Expr expr_ = p.expr_.accept(this, arg);
      return new stella.Absyn.Pred(expr_);
    }
    public stella.Absyn.Expr visit(stella.Absyn.IsZero p, A arg)
    {
      stella.Absyn.Expr expr_ = p.expr_.accept(this, arg);
      return new stella.Absyn.IsZero(expr_);
    }
    public stella.Absyn.Expr visit(stella.Absyn.Fix p, A arg)
    {
      stella.Absyn.Expr expr_ = p.expr_.accept(this, arg);
      return new stella.Absyn.Fix(expr_);
    }
    public stella.Absyn.Expr visit(stella.Absyn.NatRec p, A arg)
    {
      stella.Absyn.Expr expr_1 = p.expr_1.accept(this, arg);
      stella.Absyn.Expr expr_2 = p.expr_2.accept(this, arg);
      stella.Absyn.Expr expr_3 = p.expr_3.accept(this, arg);
      return new stella.Absyn.NatRec(expr_1, expr_2, expr_3);
    }
    public stella.Absyn.Expr visit(stella.Absyn.Fold p, A arg)
    {
      stella.Absyn.Type type_ = p.type_.accept(this, arg);
      stella.Absyn.Expr expr_ = p.expr_.accept(this, arg);
      return new stella.Absyn.Fold(type_, expr_);
    }
    public stella.Absyn.Expr visit(stella.Absyn.Unfold p, A arg)
    {
      stella.Absyn.Type type_ = p.type_.accept(this, arg);
      stella.Absyn.Expr expr_ = p.expr_.accept(this, arg);
      return new stella.Absyn.Unfold(type_, expr_);
    }
    public stella.Absyn.Expr visit(stella.Absyn.DotRecord p, A arg)
    {
      stella.Absyn.Expr expr_ = p.expr_.accept(this, arg);
      String stellaident_ = p.stellaident_;
      return new stella.Absyn.DotRecord(expr_, stellaident_);
    }
    public stella.Absyn.Expr visit(stella.Absyn.DotTuple p, A arg)
    {
      stella.Absyn.Expr expr_ = p.expr_.accept(this, arg);
      Integer integer_ = p.integer_;
      return new stella.Absyn.DotTuple(expr_, integer_);
    }
    public stella.Absyn.Expr visit(stella.Absyn.ConstTrue p, A arg)
    {
      return new stella.Absyn.ConstTrue();
    }
    public stella.Absyn.Expr visit(stella.Absyn.ConstFalse p, A arg)
    {
      return new stella.Absyn.ConstFalse();
    }
    public stella.Absyn.Expr visit(stella.Absyn.ConstInt p, A arg)
    {
      Integer integer_ = p.integer_;
      return new stella.Absyn.ConstInt(integer_);
    }
    public stella.Absyn.Expr visit(stella.Absyn.Var p, A arg)
    {
      String stellaident_ = p.stellaident_;
      return new stella.Absyn.Var(stellaident_);
    }

    /* MatchCase */
    public stella.Absyn.MatchCase visit(stella.Absyn.AMatchCase p, A arg)
    {
      stella.Absyn.Pattern pattern_ = p.pattern_.accept(this, arg);
      stella.Absyn.Expr expr_ = p.expr_.accept(this, arg);
      return new stella.Absyn.AMatchCase(pattern_, expr_);
    }

    /* OptionalTyping */
    public stella.Absyn.OptionalTyping visit(stella.Absyn.NoTyping p, A arg)
    {
      return new stella.Absyn.NoTyping();
    }
    public stella.Absyn.OptionalTyping visit(stella.Absyn.SomeTyping p, A arg)
    {
      stella.Absyn.Type type_ = p.type_.accept(this, arg);
      return new stella.Absyn.SomeTyping(type_);
    }

    /* PatternData */
    public stella.Absyn.PatternData visit(stella.Absyn.NoPatternData p, A arg)
    {
      return new stella.Absyn.NoPatternData();
    }
    public stella.Absyn.PatternData visit(stella.Absyn.SomePatternData p, A arg)
    {
      stella.Absyn.Pattern pattern_ = p.pattern_.accept(this, arg);
      return new stella.Absyn.SomePatternData(pattern_);
    }

    /* ExprData */
    public stella.Absyn.ExprData visit(stella.Absyn.NoExprData p, A arg)
    {
      return new stella.Absyn.NoExprData();
    }
    public stella.Absyn.ExprData visit(stella.Absyn.SomeExprData p, A arg)
    {
      stella.Absyn.Expr expr_ = p.expr_.accept(this, arg);
      return new stella.Absyn.SomeExprData(expr_);
    }

    /* Pattern */
    public stella.Absyn.Pattern visit(stella.Absyn.PatternVariant p, A arg)
    {
      String stellaident_ = p.stellaident_;
      stella.Absyn.PatternData patterndata_ = p.patterndata_.accept(this, arg);
      return new stella.Absyn.PatternVariant(stellaident_, patterndata_);
    }
    public stella.Absyn.Pattern visit(stella.Absyn.PatternTuple p, A arg)
    {
      stella.Absyn.ListPattern listpattern_ = new stella.Absyn.ListPattern();
      for (stella.Absyn.Pattern x : p.listpattern_)
      {
        listpattern_.add(x.accept(this,arg));
      }
      return new stella.Absyn.PatternTuple(listpattern_);
    }
    public stella.Absyn.Pattern visit(stella.Absyn.PatternRecord p, A arg)
    {
      stella.Absyn.ListLabelledPattern listlabelledpattern_ = new stella.Absyn.ListLabelledPattern();
      for (stella.Absyn.LabelledPattern x : p.listlabelledpattern_)
      {
        listlabelledpattern_.add(x.accept(this,arg));
      }
      return new stella.Absyn.PatternRecord(listlabelledpattern_);
    }
    public stella.Absyn.Pattern visit(stella.Absyn.PatternList p, A arg)
    {
      stella.Absyn.ListPattern listpattern_ = new stella.Absyn.ListPattern();
      for (stella.Absyn.Pattern x : p.listpattern_)
      {
        listpattern_.add(x.accept(this,arg));
      }
      return new stella.Absyn.PatternList(listpattern_);
    }
    public stella.Absyn.Pattern visit(stella.Absyn.PatternCons p, A arg)
    {
      stella.Absyn.Pattern pattern_1 = p.pattern_1.accept(this, arg);
      stella.Absyn.Pattern pattern_2 = p.pattern_2.accept(this, arg);
      return new stella.Absyn.PatternCons(pattern_1, pattern_2);
    }
    public stella.Absyn.Pattern visit(stella.Absyn.PatternFalse p, A arg)
    {
      return new stella.Absyn.PatternFalse();
    }
    public stella.Absyn.Pattern visit(stella.Absyn.PatternTrue p, A arg)
    {
      return new stella.Absyn.PatternTrue();
    }
    public stella.Absyn.Pattern visit(stella.Absyn.PatternInt p, A arg)
    {
      Integer integer_ = p.integer_;
      return new stella.Absyn.PatternInt(integer_);
    }
    public stella.Absyn.Pattern visit(stella.Absyn.PatternSucc p, A arg)
    {
      stella.Absyn.Pattern pattern_ = p.pattern_.accept(this, arg);
      return new stella.Absyn.PatternSucc(pattern_);
    }
    public stella.Absyn.Pattern visit(stella.Absyn.PatternVar p, A arg)
    {
      String stellaident_ = p.stellaident_;
      return new stella.Absyn.PatternVar(stellaident_);
    }

    /* LabelledPattern */
    public stella.Absyn.LabelledPattern visit(stella.Absyn.ALabelledPattern p, A arg)
    {
      String stellaident_ = p.stellaident_;
      stella.Absyn.Pattern pattern_ = p.pattern_.accept(this, arg);
      return new stella.Absyn.ALabelledPattern(stellaident_, pattern_);
    }

    /* Binding */
    public stella.Absyn.Binding visit(stella.Absyn.ABinding p, A arg)
    {
      String stellaident_ = p.stellaident_;
      stella.Absyn.Expr expr_ = p.expr_.accept(this, arg);
      return new stella.Absyn.ABinding(stellaident_, expr_);
    }

    /* Type */
    public stella.Absyn.Type visit(stella.Absyn.TypeFun p, A arg)
    {
      stella.Absyn.ListType listtype_ = new stella.Absyn.ListType();
      for (stella.Absyn.Type x : p.listtype_)
      {
        listtype_.add(x.accept(this,arg));
      }
      stella.Absyn.Type type_ = p.type_.accept(this, arg);
      return new stella.Absyn.TypeFun(listtype_, type_);
    }
    public stella.Absyn.Type visit(stella.Absyn.TypeRec p, A arg)
    {
      String stellaident_ = p.stellaident_;
      stella.Absyn.Type type_ = p.type_.accept(this, arg);
      return new stella.Absyn.TypeRec(stellaident_, type_);
    }
    public stella.Absyn.Type visit(stella.Absyn.TypeSum p, A arg)
    {
      stella.Absyn.Type type_1 = p.type_1.accept(this, arg);
      stella.Absyn.Type type_2 = p.type_2.accept(this, arg);
      return new stella.Absyn.TypeSum(type_1, type_2);
    }
    public stella.Absyn.Type visit(stella.Absyn.TypeTuple p, A arg)
    {
      stella.Absyn.ListType listtype_ = new stella.Absyn.ListType();
      for (stella.Absyn.Type x : p.listtype_)
      {
        listtype_.add(x.accept(this,arg));
      }
      return new stella.Absyn.TypeTuple(listtype_);
    }
    public stella.Absyn.Type visit(stella.Absyn.TypeRecord p, A arg)
    {
      stella.Absyn.ListRecordFieldType listrecordfieldtype_ = new stella.Absyn.ListRecordFieldType();
      for (stella.Absyn.RecordFieldType x : p.listrecordfieldtype_)
      {
        listrecordfieldtype_.add(x.accept(this,arg));
      }
      return new stella.Absyn.TypeRecord(listrecordfieldtype_);
    }
    public stella.Absyn.Type visit(stella.Absyn.TypeVariant p, A arg)
    {
      stella.Absyn.ListVariantFieldType listvariantfieldtype_ = new stella.Absyn.ListVariantFieldType();
      for (stella.Absyn.VariantFieldType x : p.listvariantfieldtype_)
      {
        listvariantfieldtype_.add(x.accept(this,arg));
      }
      return new stella.Absyn.TypeVariant(listvariantfieldtype_);
    }
    public stella.Absyn.Type visit(stella.Absyn.TypeList p, A arg)
    {
      stella.Absyn.Type type_ = p.type_.accept(this, arg);
      return new stella.Absyn.TypeList(type_);
    }
    public stella.Absyn.Type visit(stella.Absyn.TypeBool p, A arg)
    {
      return new stella.Absyn.TypeBool();
    }
    public stella.Absyn.Type visit(stella.Absyn.TypeNat p, A arg)
    {
      return new stella.Absyn.TypeNat();
    }
    public stella.Absyn.Type visit(stella.Absyn.TypeUnit p, A arg)
    {
      return new stella.Absyn.TypeUnit();
    }
    public stella.Absyn.Type visit(stella.Absyn.TypeVar p, A arg)
    {
      String stellaident_ = p.stellaident_;
      return new stella.Absyn.TypeVar(stellaident_);
    }

    /* VariantFieldType */
    public stella.Absyn.VariantFieldType visit(stella.Absyn.AVariantFieldType p, A arg)
    {
      String stellaident_ = p.stellaident_;
      stella.Absyn.OptionalTyping optionaltyping_ = p.optionaltyping_.accept(this, arg);
      return new stella.Absyn.AVariantFieldType(stellaident_, optionaltyping_);
    }

    /* RecordFieldType */
    public stella.Absyn.RecordFieldType visit(stella.Absyn.ARecordFieldType p, A arg)
    {
      String stellaident_ = p.stellaident_;
      stella.Absyn.Type type_ = p.type_.accept(this, arg);
      return new stella.Absyn.ARecordFieldType(stellaident_, type_);
    }

    /* Typing */
    public stella.Absyn.Typing visit(stella.Absyn.ATyping p, A arg)
    {
      stella.Absyn.Expr expr_ = p.expr_.accept(this, arg);
      stella.Absyn.Type type_ = p.type_.accept(this, arg);
      return new stella.Absyn.ATyping(expr_, type_);
    }
}
