// File generated by the BNF Converter (bnfc 2.9.4.1).

package stella;

/** Fold Visitor */
public abstract class FoldVisitor<R,A> implements AllVisitor<R,A> {
    public abstract R leaf(A arg);
    public abstract R combine(R x, R y, A arg);

/* Program */
    public R visit(stella.Absyn.AProgram p, A arg) {
      R r = leaf(arg);
      r = combine(p.languagedecl_.accept(this, arg), r, arg);
      for (stella.Absyn.Extension x : p.listextension_)
      {
        r = combine(x.accept(this, arg), r, arg);
      }
      for (stella.Absyn.Decl x : p.listdecl_)
      {
        r = combine(x.accept(this, arg), r, arg);
      }
      return r;
    }

/* LanguageDecl */
    public R visit(stella.Absyn.LanguageCore p, A arg) {
      R r = leaf(arg);
      return r;
    }

/* Extension */
    public R visit(stella.Absyn.AnExtension p, A arg) {
      R r = leaf(arg);
      return r;
    }

/* Decl */
    public R visit(stella.Absyn.DeclFun p, A arg) {
      R r = leaf(arg);
      for (stella.Absyn.Annotation x : p.listannotation_)
      {
        r = combine(x.accept(this, arg), r, arg);
      }
      for (stella.Absyn.ParamDecl x : p.listparamdecl_)
      {
        r = combine(x.accept(this, arg), r, arg);
      }
      r = combine(p.returntype_.accept(this, arg), r, arg);
      r = combine(p.throwtype_.accept(this, arg), r, arg);
      for (stella.Absyn.Decl x : p.listdecl_)
      {
        r = combine(x.accept(this, arg), r, arg);
      }
      r = combine(p.expr_.accept(this, arg), r, arg);
      return r;
    }
    public R visit(stella.Absyn.DeclTypeAlias p, A arg) {
      R r = leaf(arg);
      r = combine(p.type_.accept(this, arg), r, arg);
      return r;
    }

/* LocalDecl */
    public R visit(stella.Absyn.ALocalDecl p, A arg) {
      R r = leaf(arg);
      r = combine(p.decl_.accept(this, arg), r, arg);
      return r;
    }

/* Annotation */
    public R visit(stella.Absyn.InlineAnnotation p, A arg) {
      R r = leaf(arg);
      return r;
    }

/* ParamDecl */
    public R visit(stella.Absyn.AParamDecl p, A arg) {
      R r = leaf(arg);
      r = combine(p.type_.accept(this, arg), r, arg);
      return r;
    }

/* ReturnType */
    public R visit(stella.Absyn.NoReturnType p, A arg) {
      R r = leaf(arg);
      return r;
    }
    public R visit(stella.Absyn.SomeReturnType p, A arg) {
      R r = leaf(arg);
      r = combine(p.type_.accept(this, arg), r, arg);
      return r;
    }

/* ThrowType */
    public R visit(stella.Absyn.NoThrowType p, A arg) {
      R r = leaf(arg);
      return r;
    }
    public R visit(stella.Absyn.SomeThrowType p, A arg) {
      R r = leaf(arg);
      for (stella.Absyn.Type x : p.listtype_)
      {
        r = combine(x.accept(this, arg), r, arg);
      }
      return r;
    }

/* Expr */
    public R visit(stella.Absyn.If p, A arg) {
      R r = leaf(arg);
      r = combine(p.expr_1.accept(this, arg), r, arg);
      r = combine(p.expr_2.accept(this, arg), r, arg);
      r = combine(p.expr_3.accept(this, arg), r, arg);
      return r;
    }
    public R visit(stella.Absyn.Let p, A arg) {
      R r = leaf(arg);
      r = combine(p.expr_1.accept(this, arg), r, arg);
      r = combine(p.expr_2.accept(this, arg), r, arg);
      return r;
    }
    public R visit(stella.Absyn.LessThan p, A arg) {
      R r = leaf(arg);
      r = combine(p.expr_1.accept(this, arg), r, arg);
      r = combine(p.expr_2.accept(this, arg), r, arg);
      return r;
    }
    public R visit(stella.Absyn.LessThanOrEqual p, A arg) {
      R r = leaf(arg);
      r = combine(p.expr_1.accept(this, arg), r, arg);
      r = combine(p.expr_2.accept(this, arg), r, arg);
      return r;
    }
    public R visit(stella.Absyn.GreaterThan p, A arg) {
      R r = leaf(arg);
      r = combine(p.expr_1.accept(this, arg), r, arg);
      r = combine(p.expr_2.accept(this, arg), r, arg);
      return r;
    }
    public R visit(stella.Absyn.GreaterThanOrEqual p, A arg) {
      R r = leaf(arg);
      r = combine(p.expr_1.accept(this, arg), r, arg);
      r = combine(p.expr_2.accept(this, arg), r, arg);
      return r;
    }
    public R visit(stella.Absyn.Equal p, A arg) {
      R r = leaf(arg);
      r = combine(p.expr_1.accept(this, arg), r, arg);
      r = combine(p.expr_2.accept(this, arg), r, arg);
      return r;
    }
    public R visit(stella.Absyn.NotEqual p, A arg) {
      R r = leaf(arg);
      r = combine(p.expr_1.accept(this, arg), r, arg);
      r = combine(p.expr_2.accept(this, arg), r, arg);
      return r;
    }
    public R visit(stella.Absyn.TypeAsc p, A arg) {
      R r = leaf(arg);
      r = combine(p.expr_.accept(this, arg), r, arg);
      r = combine(p.type_.accept(this, arg), r, arg);
      return r;
    }
    public R visit(stella.Absyn.Abstraction p, A arg) {
      R r = leaf(arg);
      for (stella.Absyn.ParamDecl x : p.listparamdecl_)
      {
        r = combine(x.accept(this, arg), r, arg);
      }
      r = combine(p.expr_.accept(this, arg), r, arg);
      return r;
    }
    public R visit(stella.Absyn.Tuple p, A arg) {
      R r = leaf(arg);
      for (stella.Absyn.Expr x : p.listexpr_)
      {
        r = combine(x.accept(this, arg), r, arg);
      }
      return r;
    }
    public R visit(stella.Absyn.Record p, A arg) {
      R r = leaf(arg);
      for (stella.Absyn.Binding x : p.listbinding_)
      {
        r = combine(x.accept(this, arg), r, arg);
      }
      return r;
    }
    public R visit(stella.Absyn.Variant p, A arg) {
      R r = leaf(arg);
      r = combine(p.exprdata_.accept(this, arg), r, arg);
      return r;
    }
    public R visit(stella.Absyn.Match p, A arg) {
      R r = leaf(arg);
      r = combine(p.expr_.accept(this, arg), r, arg);
      for (stella.Absyn.MatchCase x : p.listmatchcase_)
      {
        r = combine(x.accept(this, arg), r, arg);
      }
      return r;
    }
    public R visit(stella.Absyn.List p, A arg) {
      R r = leaf(arg);
      for (stella.Absyn.Expr x : p.listexpr_)
      {
        r = combine(x.accept(this, arg), r, arg);
      }
      return r;
    }
    public R visit(stella.Absyn.Add p, A arg) {
      R r = leaf(arg);
      r = combine(p.expr_1.accept(this, arg), r, arg);
      r = combine(p.expr_2.accept(this, arg), r, arg);
      return r;
    }
    public R visit(stella.Absyn.LogicOr p, A arg) {
      R r = leaf(arg);
      r = combine(p.expr_1.accept(this, arg), r, arg);
      r = combine(p.expr_2.accept(this, arg), r, arg);
      return r;
    }
    public R visit(stella.Absyn.Multiply p, A arg) {
      R r = leaf(arg);
      r = combine(p.expr_1.accept(this, arg), r, arg);
      r = combine(p.expr_2.accept(this, arg), r, arg);
      return r;
    }
    public R visit(stella.Absyn.LogicAnd p, A arg) {
      R r = leaf(arg);
      r = combine(p.expr_1.accept(this, arg), r, arg);
      r = combine(p.expr_2.accept(this, arg), r, arg);
      return r;
    }
    public R visit(stella.Absyn.Application p, A arg) {
      R r = leaf(arg);
      r = combine(p.expr_.accept(this, arg), r, arg);
      for (stella.Absyn.Expr x : p.listexpr_)
      {
        r = combine(x.accept(this, arg), r, arg);
      }
      return r;
    }
    public R visit(stella.Absyn.ConsList p, A arg) {
      R r = leaf(arg);
      r = combine(p.expr_1.accept(this, arg), r, arg);
      r = combine(p.expr_2.accept(this, arg), r, arg);
      return r;
    }
    public R visit(stella.Absyn.Head p, A arg) {
      R r = leaf(arg);
      r = combine(p.expr_.accept(this, arg), r, arg);
      return r;
    }
    public R visit(stella.Absyn.IsEmpty p, A arg) {
      R r = leaf(arg);
      r = combine(p.expr_.accept(this, arg), r, arg);
      return r;
    }
    public R visit(stella.Absyn.Tail p, A arg) {
      R r = leaf(arg);
      r = combine(p.expr_.accept(this, arg), r, arg);
      return r;
    }
    public R visit(stella.Absyn.Succ p, A arg) {
      R r = leaf(arg);
      r = combine(p.expr_.accept(this, arg), r, arg);
      return r;
    }
    public R visit(stella.Absyn.LogicNot p, A arg) {
      R r = leaf(arg);
      r = combine(p.expr_.accept(this, arg), r, arg);
      return r;
    }
    public R visit(stella.Absyn.Pred p, A arg) {
      R r = leaf(arg);
      r = combine(p.expr_.accept(this, arg), r, arg);
      return r;
    }
    public R visit(stella.Absyn.IsZero p, A arg) {
      R r = leaf(arg);
      r = combine(p.expr_.accept(this, arg), r, arg);
      return r;
    }
    public R visit(stella.Absyn.Fix p, A arg) {
      R r = leaf(arg);
      r = combine(p.expr_.accept(this, arg), r, arg);
      return r;
    }
    public R visit(stella.Absyn.NatRec p, A arg) {
      R r = leaf(arg);
      r = combine(p.expr_1.accept(this, arg), r, arg);
      r = combine(p.expr_2.accept(this, arg), r, arg);
      r = combine(p.expr_3.accept(this, arg), r, arg);
      return r;
    }
    public R visit(stella.Absyn.Fold p, A arg) {
      R r = leaf(arg);
      r = combine(p.type_.accept(this, arg), r, arg);
      r = combine(p.expr_.accept(this, arg), r, arg);
      return r;
    }
    public R visit(stella.Absyn.Unfold p, A arg) {
      R r = leaf(arg);
      r = combine(p.type_.accept(this, arg), r, arg);
      r = combine(p.expr_.accept(this, arg), r, arg);
      return r;
    }
    public R visit(stella.Absyn.DotRecord p, A arg) {
      R r = leaf(arg);
      r = combine(p.expr_.accept(this, arg), r, arg);
      return r;
    }
    public R visit(stella.Absyn.DotTuple p, A arg) {
      R r = leaf(arg);
      r = combine(p.expr_.accept(this, arg), r, arg);
      return r;
    }
    public R visit(stella.Absyn.ConstTrue p, A arg) {
      R r = leaf(arg);
      return r;
    }
    public R visit(stella.Absyn.ConstFalse p, A arg) {
      R r = leaf(arg);
      return r;
    }
    public R visit(stella.Absyn.ConstInt p, A arg) {
      R r = leaf(arg);
      return r;
    }
    public R visit(stella.Absyn.Var p, A arg) {
      R r = leaf(arg);
      return r;
    }

/* MatchCase */
    public R visit(stella.Absyn.AMatchCase p, A arg) {
      R r = leaf(arg);
      r = combine(p.pattern_.accept(this, arg), r, arg);
      r = combine(p.expr_.accept(this, arg), r, arg);
      return r;
    }

/* OptionalTyping */
    public R visit(stella.Absyn.NoTyping p, A arg) {
      R r = leaf(arg);
      return r;
    }
    public R visit(stella.Absyn.SomeTyping p, A arg) {
      R r = leaf(arg);
      r = combine(p.type_.accept(this, arg), r, arg);
      return r;
    }

/* PatternData */
    public R visit(stella.Absyn.NoPatternData p, A arg) {
      R r = leaf(arg);
      return r;
    }
    public R visit(stella.Absyn.SomePatternData p, A arg) {
      R r = leaf(arg);
      r = combine(p.pattern_.accept(this, arg), r, arg);
      return r;
    }

/* ExprData */
    public R visit(stella.Absyn.NoExprData p, A arg) {
      R r = leaf(arg);
      return r;
    }
    public R visit(stella.Absyn.SomeExprData p, A arg) {
      R r = leaf(arg);
      r = combine(p.expr_.accept(this, arg), r, arg);
      return r;
    }

/* Pattern */
    public R visit(stella.Absyn.PatternVariant p, A arg) {
      R r = leaf(arg);
      r = combine(p.patterndata_.accept(this, arg), r, arg);
      return r;
    }
    public R visit(stella.Absyn.PatternTuple p, A arg) {
      R r = leaf(arg);
      for (stella.Absyn.Pattern x : p.listpattern_)
      {
        r = combine(x.accept(this, arg), r, arg);
      }
      return r;
    }
    public R visit(stella.Absyn.PatternRecord p, A arg) {
      R r = leaf(arg);
      for (stella.Absyn.LabelledPattern x : p.listlabelledpattern_)
      {
        r = combine(x.accept(this, arg), r, arg);
      }
      return r;
    }
    public R visit(stella.Absyn.PatternList p, A arg) {
      R r = leaf(arg);
      for (stella.Absyn.Pattern x : p.listpattern_)
      {
        r = combine(x.accept(this, arg), r, arg);
      }
      return r;
    }
    public R visit(stella.Absyn.PatternCons p, A arg) {
      R r = leaf(arg);
      r = combine(p.pattern_1.accept(this, arg), r, arg);
      r = combine(p.pattern_2.accept(this, arg), r, arg);
      return r;
    }
    public R visit(stella.Absyn.PatternFalse p, A arg) {
      R r = leaf(arg);
      return r;
    }
    public R visit(stella.Absyn.PatternTrue p, A arg) {
      R r = leaf(arg);
      return r;
    }
    public R visit(stella.Absyn.PatternInt p, A arg) {
      R r = leaf(arg);
      return r;
    }
    public R visit(stella.Absyn.PatternSucc p, A arg) {
      R r = leaf(arg);
      r = combine(p.pattern_.accept(this, arg), r, arg);
      return r;
    }
    public R visit(stella.Absyn.PatternVar p, A arg) {
      R r = leaf(arg);
      return r;
    }

/* LabelledPattern */
    public R visit(stella.Absyn.ALabelledPattern p, A arg) {
      R r = leaf(arg);
      r = combine(p.pattern_.accept(this, arg), r, arg);
      return r;
    }

/* Binding */
    public R visit(stella.Absyn.ABinding p, A arg) {
      R r = leaf(arg);
      r = combine(p.expr_.accept(this, arg), r, arg);
      return r;
    }

/* Type */
    public R visit(stella.Absyn.TypeFun p, A arg) {
      R r = leaf(arg);
      for (stella.Absyn.Type x : p.listtype_)
      {
        r = combine(x.accept(this, arg), r, arg);
      }
      r = combine(p.type_.accept(this, arg), r, arg);
      return r;
    }
    public R visit(stella.Absyn.TypeRec p, A arg) {
      R r = leaf(arg);
      r = combine(p.type_.accept(this, arg), r, arg);
      return r;
    }
    public R visit(stella.Absyn.TypeSum p, A arg) {
      R r = leaf(arg);
      r = combine(p.type_1.accept(this, arg), r, arg);
      r = combine(p.type_2.accept(this, arg), r, arg);
      return r;
    }
    public R visit(stella.Absyn.TypeTuple p, A arg) {
      R r = leaf(arg);
      for (stella.Absyn.Type x : p.listtype_)
      {
        r = combine(x.accept(this, arg), r, arg);
      }
      return r;
    }
    public R visit(stella.Absyn.TypeRecord p, A arg) {
      R r = leaf(arg);
      for (stella.Absyn.RecordFieldType x : p.listrecordfieldtype_)
      {
        r = combine(x.accept(this, arg), r, arg);
      }
      return r;
    }
    public R visit(stella.Absyn.TypeVariant p, A arg) {
      R r = leaf(arg);
      for (stella.Absyn.VariantFieldType x : p.listvariantfieldtype_)
      {
        r = combine(x.accept(this, arg), r, arg);
      }
      return r;
    }
    public R visit(stella.Absyn.TypeList p, A arg) {
      R r = leaf(arg);
      r = combine(p.type_.accept(this, arg), r, arg);
      return r;
    }
    public R visit(stella.Absyn.TypeBool p, A arg) {
      R r = leaf(arg);
      return r;
    }
    public R visit(stella.Absyn.TypeNat p, A arg) {
      R r = leaf(arg);
      return r;
    }
    public R visit(stella.Absyn.TypeUnit p, A arg) {
      R r = leaf(arg);
      return r;
    }
    public R visit(stella.Absyn.TypeVar p, A arg) {
      R r = leaf(arg);
      return r;
    }

/* VariantFieldType */
    public R visit(stella.Absyn.AVariantFieldType p, A arg) {
      R r = leaf(arg);
      r = combine(p.optionaltyping_.accept(this, arg), r, arg);
      return r;
    }

/* RecordFieldType */
    public R visit(stella.Absyn.ARecordFieldType p, A arg) {
      R r = leaf(arg);
      r = combine(p.type_.accept(this, arg), r, arg);
      return r;
    }

/* Typing */
    public R visit(stella.Absyn.ATyping p, A arg) {
      R r = leaf(arg);
      r = combine(p.expr_.accept(this, arg), r, arg);
      r = combine(p.type_.accept(this, arg), r, arg);
      return r;
    }


}
