// File generated by the BNF Converter (bnfc 2.9.4.1).

package stella;

public class PrettyPrinter
{
  //For certain applications increasing the initial size of the buffer may improve performance.
  private static final int INITIAL_BUFFER_SIZE = 128;
  private static final int INDENT_WIDTH = 2;
  //You may wish to change the parentheses used in precedence.
  private static final String _L_PAREN = new String("(");
  private static final String _R_PAREN = new String(")");
  //You may wish to change render
  private static void render(String s)
  {
    if (s.equals("{"))
    {
       onEmptyLine();
       buf_.append(s);
       _n_ = _n_ + INDENT_WIDTH;
       buf_.append("\n");
       indent();
    }
    else if (s.equals("(") || s.equals("["))
       buf_.append(s);
    else if (s.equals(")") || s.equals("]"))
    {
       removeTrailingWhitespace();
       buf_.append(s);
       buf_.append(" ");
    }
    else if (s.equals("}"))
    {
       _n_ = _n_ - INDENT_WIDTH;
       onEmptyLine();
       buf_.append(s);
       buf_.append("\n");
       indent();
    }
    else if (s.equals(","))
    {
       removeTrailingWhitespace();
       buf_.append(s);
       buf_.append(" ");
    }
    else if (s.equals(";"))
    {
       removeTrailingWhitespace();
       buf_.append(s);
       buf_.append("\n");
       indent();
    }
    else if (s.equals("")) return;
    else if (s.trim().equals(""))
    {
       backup();
       buf_.append(s);
    }
    else
    {
       buf_.append(s);
       buf_.append(" ");
    }
  }


  //  print and show methods are defined for each category.
  public static String print(stella.Absyn.ListStellaIdent foo)
  {
    pp(foo, 0);
    trim();
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String show(stella.Absyn.ListStellaIdent foo)
  {
    sh(foo);
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String print(stella.Absyn.Program foo)
  {
    pp(foo, 0);
    trim();
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String show(stella.Absyn.Program foo)
  {
    sh(foo);
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String print(stella.Absyn.LanguageDecl foo)
  {
    pp(foo, 0);
    trim();
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String show(stella.Absyn.LanguageDecl foo)
  {
    sh(foo);
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String print(stella.Absyn.Extension foo)
  {
    pp(foo, 0);
    trim();
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String show(stella.Absyn.Extension foo)
  {
    sh(foo);
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String print(stella.Absyn.ListExtensionName foo)
  {
    pp(foo, 0);
    trim();
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String show(stella.Absyn.ListExtensionName foo)
  {
    sh(foo);
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String print(stella.Absyn.ListExtension foo)
  {
    pp(foo, 0);
    trim();
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String show(stella.Absyn.ListExtension foo)
  {
    sh(foo);
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String print(stella.Absyn.Decl foo)
  {
    pp(foo, 0);
    trim();
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String show(stella.Absyn.Decl foo)
  {
    sh(foo);
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String print(stella.Absyn.ListDecl foo)
  {
    pp(foo, 0);
    trim();
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String show(stella.Absyn.ListDecl foo)
  {
    sh(foo);
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String print(stella.Absyn.LocalDecl foo)
  {
    pp(foo, 0);
    trim();
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String show(stella.Absyn.LocalDecl foo)
  {
    sh(foo);
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String print(stella.Absyn.ListLocalDecl foo)
  {
    pp(foo, 0);
    trim();
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String show(stella.Absyn.ListLocalDecl foo)
  {
    sh(foo);
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String print(stella.Absyn.Annotation foo)
  {
    pp(foo, 0);
    trim();
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String show(stella.Absyn.Annotation foo)
  {
    sh(foo);
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String print(stella.Absyn.ListAnnotation foo)
  {
    pp(foo, 0);
    trim();
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String show(stella.Absyn.ListAnnotation foo)
  {
    sh(foo);
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String print(stella.Absyn.ParamDecl foo)
  {
    pp(foo, 0);
    trim();
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String show(stella.Absyn.ParamDecl foo)
  {
    sh(foo);
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String print(stella.Absyn.ListParamDecl foo)
  {
    pp(foo, 0);
    trim();
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String show(stella.Absyn.ListParamDecl foo)
  {
    sh(foo);
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String print(stella.Absyn.ReturnType foo)
  {
    pp(foo, 0);
    trim();
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String show(stella.Absyn.ReturnType foo)
  {
    sh(foo);
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String print(stella.Absyn.ThrowType foo)
  {
    pp(foo, 0);
    trim();
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String show(stella.Absyn.ThrowType foo)
  {
    sh(foo);
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String print(stella.Absyn.Expr foo)
  {
    pp(foo, 0);
    trim();
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String show(stella.Absyn.Expr foo)
  {
    sh(foo);
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String print(stella.Absyn.ListExpr foo)
  {
    pp(foo, 0);
    trim();
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String show(stella.Absyn.ListExpr foo)
  {
    sh(foo);
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String print(stella.Absyn.MatchCase foo)
  {
    pp(foo, 0);
    trim();
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String show(stella.Absyn.MatchCase foo)
  {
    sh(foo);
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String print(stella.Absyn.ListMatchCase foo)
  {
    pp(foo, 0);
    trim();
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String show(stella.Absyn.ListMatchCase foo)
  {
    sh(foo);
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String print(stella.Absyn.OptionalTyping foo)
  {
    pp(foo, 0);
    trim();
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String show(stella.Absyn.OptionalTyping foo)
  {
    sh(foo);
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String print(stella.Absyn.PatternData foo)
  {
    pp(foo, 0);
    trim();
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String show(stella.Absyn.PatternData foo)
  {
    sh(foo);
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String print(stella.Absyn.ExprData foo)
  {
    pp(foo, 0);
    trim();
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String show(stella.Absyn.ExprData foo)
  {
    sh(foo);
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String print(stella.Absyn.Pattern foo)
  {
    pp(foo, 0);
    trim();
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String show(stella.Absyn.Pattern foo)
  {
    sh(foo);
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String print(stella.Absyn.ListPattern foo)
  {
    pp(foo, 0);
    trim();
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String show(stella.Absyn.ListPattern foo)
  {
    sh(foo);
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String print(stella.Absyn.LabelledPattern foo)
  {
    pp(foo, 0);
    trim();
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String show(stella.Absyn.LabelledPattern foo)
  {
    sh(foo);
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String print(stella.Absyn.ListLabelledPattern foo)
  {
    pp(foo, 0);
    trim();
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String show(stella.Absyn.ListLabelledPattern foo)
  {
    sh(foo);
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String print(stella.Absyn.Binding foo)
  {
    pp(foo, 0);
    trim();
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String show(stella.Absyn.Binding foo)
  {
    sh(foo);
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String print(stella.Absyn.ListBinding foo)
  {
    pp(foo, 0);
    trim();
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String show(stella.Absyn.ListBinding foo)
  {
    sh(foo);
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String print(stella.Absyn.Type foo)
  {
    pp(foo, 0);
    trim();
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String show(stella.Absyn.Type foo)
  {
    sh(foo);
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String print(stella.Absyn.ListType foo)
  {
    pp(foo, 0);
    trim();
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String show(stella.Absyn.ListType foo)
  {
    sh(foo);
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String print(stella.Absyn.VariantFieldType foo)
  {
    pp(foo, 0);
    trim();
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String show(stella.Absyn.VariantFieldType foo)
  {
    sh(foo);
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String print(stella.Absyn.ListVariantFieldType foo)
  {
    pp(foo, 0);
    trim();
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String show(stella.Absyn.ListVariantFieldType foo)
  {
    sh(foo);
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String print(stella.Absyn.RecordFieldType foo)
  {
    pp(foo, 0);
    trim();
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String show(stella.Absyn.RecordFieldType foo)
  {
    sh(foo);
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String print(stella.Absyn.ListRecordFieldType foo)
  {
    pp(foo, 0);
    trim();
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String show(stella.Absyn.ListRecordFieldType foo)
  {
    sh(foo);
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String print(stella.Absyn.Typing foo)
  {
    pp(foo, 0);
    trim();
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String show(stella.Absyn.Typing foo)
  {
    sh(foo);
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  /***   You shouldn't need to change anything beyond this point.   ***/

  private static void pp(stella.Absyn.ListStellaIdent foo, int _i_)
  {
    ppListStellaIdent(foo.iterator(), _i_);
  }

  private static void ppListStellaIdent(java.util.Iterator<String> it, int _i_)
  {
    if (it.hasNext())
    {
      String el = it.next();
      if (!it.hasNext())
      { /* last */
        pp(el, _i_);
      }
      else
      { /* cons */
        pp(el, _i_); render(","); ppListStellaIdent(it, _i_);
      }
    }
  }


  private static void pp(stella.Absyn.Program foo, int _i_)
  {
    if (foo instanceof stella.Absyn.AProgram)
    {
       stella.Absyn.AProgram _aprogram = (stella.Absyn.AProgram) foo;
       if (_i_ > 0) render(_L_PAREN);
       pp(_aprogram.languagedecl_, 0);
       pp(_aprogram.listextension_, 0);
       pp(_aprogram.listdecl_, 0);
       if (_i_ > 0) render(_R_PAREN);
    }

  }

  private static void pp(stella.Absyn.LanguageDecl foo, int _i_)
  {
    if (foo instanceof stella.Absyn.LanguageCore)
    {
       stella.Absyn.LanguageCore _languagecore = (stella.Absyn.LanguageCore) foo;
       if (_i_ > 0) render(_L_PAREN);
       render("language");
       render("core");
       render(";");
       if (_i_ > 0) render(_R_PAREN);
    }

  }

  private static void pp(stella.Absyn.Extension foo, int _i_)
  {
    if (foo instanceof stella.Absyn.AnExtension)
    {
       stella.Absyn.AnExtension _anextension = (stella.Absyn.AnExtension) foo;
       if (_i_ > 0) render(_L_PAREN);
       render("extend");
       render("with");
       pp(_anextension.listextensionname_, 0);
       if (_i_ > 0) render(_R_PAREN);
    }

  }

  private static void pp(stella.Absyn.ListExtensionName foo, int _i_)
  {
    ppListExtensionName(foo.iterator(), _i_);
  }

  private static void ppListExtensionName(java.util.Iterator<String> it, int _i_)
  {
    if (it.hasNext())
    {
      String el = it.next();
      if (!it.hasNext())
      { /* last */
        pp(el, _i_);
      }
      else
      { /* cons */
        pp(el, _i_); render(","); ppListExtensionName(it, _i_);
      }
    }
  }


  private static void pp(stella.Absyn.ListExtension foo, int _i_)
  {
    ppListExtension(foo.iterator(), _i_);
  }

  private static void ppListExtension(java.util.Iterator<stella.Absyn.Extension> it, int _i_)
  {
    if (it.hasNext())
    { /* cons */
      stella.Absyn.Extension el = it.next();
      pp(el, _i_); render(";"); ppListExtension(it, _i_);
    }
  }


  private static void pp(stella.Absyn.Decl foo, int _i_)
  {
    if (foo instanceof stella.Absyn.DeclFun)
    {
       stella.Absyn.DeclFun _declfun = (stella.Absyn.DeclFun) foo;
       if (_i_ > 0) render(_L_PAREN);
       pp(_declfun.listannotation_, 0);
       render("fn");
       pp(_declfun.stellaident_, 0);
       render("(");
       pp(_declfun.listparamdecl_, 0);
       render(")");
       pp(_declfun.returntype_, 0);
       pp(_declfun.throwtype_, 0);
       render("{");
       pp(_declfun.listdecl_, 0);
       render("return");
       pp(_declfun.expr_, 0);
       render(";");
       render("}");
       if (_i_ > 0) render(_R_PAREN);
    }
    else     if (foo instanceof stella.Absyn.DeclTypeAlias)
    {
       stella.Absyn.DeclTypeAlias _decltypealias = (stella.Absyn.DeclTypeAlias) foo;
       if (_i_ > 0) render(_L_PAREN);
       render("type");
       pp(_decltypealias.stellaident_, 0);
       render("=");
       pp(_decltypealias.type_, 0);
       if (_i_ > 0) render(_R_PAREN);
    }

  }

  private static void pp(stella.Absyn.ListDecl foo, int _i_)
  {
    ppListDecl(foo.iterator(), _i_);
  }

  private static void ppListDecl(java.util.Iterator<stella.Absyn.Decl> it, int _i_)
  {
    if (it.hasNext())
    { /* cons */
      stella.Absyn.Decl el = it.next();
      pp(el, _i_); ppListDecl(it, _i_);
    }
  }


  private static void pp(stella.Absyn.LocalDecl foo, int _i_)
  {
    if (foo instanceof stella.Absyn.ALocalDecl)
    {
       stella.Absyn.ALocalDecl _alocaldecl = (stella.Absyn.ALocalDecl) foo;
       if (_i_ > 0) render(_L_PAREN);
       pp(_alocaldecl.decl_, 0);
       if (_i_ > 0) render(_R_PAREN);
    }

  }

  private static void pp(stella.Absyn.ListLocalDecl foo, int _i_)
  {
    ppListLocalDecl(foo.iterator(), _i_);
  }

  private static void ppListLocalDecl(java.util.Iterator<stella.Absyn.LocalDecl> it, int _i_)
  {
    if (it.hasNext())
    { /* cons */
      stella.Absyn.LocalDecl el = it.next();
      pp(el, _i_); render(";"); ppListLocalDecl(it, _i_);
    }
  }


  private static void pp(stella.Absyn.Annotation foo, int _i_)
  {
    if (foo instanceof stella.Absyn.InlineAnnotation)
    {
       stella.Absyn.InlineAnnotation _inlineannotation = (stella.Absyn.InlineAnnotation) foo;
       if (_i_ > 0) render(_L_PAREN);
       render("inline");
       if (_i_ > 0) render(_R_PAREN);
    }

  }

  private static void pp(stella.Absyn.ListAnnotation foo, int _i_)
  {
    ppListAnnotation(foo.iterator(), _i_);
  }

  private static void ppListAnnotation(java.util.Iterator<stella.Absyn.Annotation> it, int _i_)
  {
    if (it.hasNext())
    { /* cons */
      stella.Absyn.Annotation el = it.next();
      pp(el, _i_); ppListAnnotation(it, _i_);
    }
  }


  private static void pp(stella.Absyn.ParamDecl foo, int _i_)
  {
    if (foo instanceof stella.Absyn.AParamDecl)
    {
       stella.Absyn.AParamDecl _aparamdecl = (stella.Absyn.AParamDecl) foo;
       if (_i_ > 0) render(_L_PAREN);
       pp(_aparamdecl.stellaident_, 0);
       render(":");
       pp(_aparamdecl.type_, 0);
       if (_i_ > 0) render(_R_PAREN);
    }

  }

  private static void pp(stella.Absyn.ListParamDecl foo, int _i_)
  {
    ppListParamDecl(foo.iterator(), _i_);
  }

  private static void ppListParamDecl(java.util.Iterator<stella.Absyn.ParamDecl> it, int _i_)
  {
    if (it.hasNext())
    {
      stella.Absyn.ParamDecl el = it.next();
      if (!it.hasNext())
      { /* last */
        pp(el, _i_);
      }
      else
      { /* cons */
        pp(el, _i_); render(","); ppListParamDecl(it, _i_);
      }
    }
  }


  private static void pp(stella.Absyn.ReturnType foo, int _i_)
  {
    if (foo instanceof stella.Absyn.NoReturnType)
    {
       stella.Absyn.NoReturnType _noreturntype = (stella.Absyn.NoReturnType) foo;
       if (_i_ > 0) render(_L_PAREN);
       if (_i_ > 0) render(_R_PAREN);
    }
    else     if (foo instanceof stella.Absyn.SomeReturnType)
    {
       stella.Absyn.SomeReturnType _somereturntype = (stella.Absyn.SomeReturnType) foo;
       if (_i_ > 0) render(_L_PAREN);
       render("->");
       pp(_somereturntype.type_, 0);
       if (_i_ > 0) render(_R_PAREN);
    }

  }

  private static void pp(stella.Absyn.ThrowType foo, int _i_)
  {
    if (foo instanceof stella.Absyn.NoThrowType)
    {
       stella.Absyn.NoThrowType _nothrowtype = (stella.Absyn.NoThrowType) foo;
       if (_i_ > 0) render(_L_PAREN);
       if (_i_ > 0) render(_R_PAREN);
    }
    else     if (foo instanceof stella.Absyn.SomeThrowType)
    {
       stella.Absyn.SomeThrowType _somethrowtype = (stella.Absyn.SomeThrowType) foo;
       if (_i_ > 0) render(_L_PAREN);
       render("throws");
       pp(_somethrowtype.listtype_, 0);
       if (_i_ > 0) render(_R_PAREN);
    }

  }

  private static void pp(stella.Absyn.Expr foo, int _i_)
  {
    if (foo instanceof stella.Absyn.If)
    {
       stella.Absyn.If _if = (stella.Absyn.If) foo;
       if (_i_ > 0) render(_L_PAREN);
       render("if");
       pp(_if.expr_1, 0);
       render("then");
       pp(_if.expr_2, 0);
       render("else");
       pp(_if.expr_3, 0);
       if (_i_ > 0) render(_R_PAREN);
    }
    else     if (foo instanceof stella.Absyn.Let)
    {
       stella.Absyn.Let _let = (stella.Absyn.Let) foo;
       if (_i_ > 0) render(_L_PAREN);
       render("let");
       pp(_let.stellaident_, 0);
       render("=");
       pp(_let.expr_1, 0);
       render("in");
       pp(_let.expr_2, 0);
       if (_i_ > 0) render(_R_PAREN);
    }
    else     if (foo instanceof stella.Absyn.LessThan)
    {
       stella.Absyn.LessThan _lessthan = (stella.Absyn.LessThan) foo;
       if (_i_ > 1) render(_L_PAREN);
       pp(_lessthan.expr_1, 2);
       render("<");
       pp(_lessthan.expr_2, 2);
       if (_i_ > 1) render(_R_PAREN);
    }
    else     if (foo instanceof stella.Absyn.LessThanOrEqual)
    {
       stella.Absyn.LessThanOrEqual _lessthanorequal = (stella.Absyn.LessThanOrEqual) foo;
       if (_i_ > 1) render(_L_PAREN);
       pp(_lessthanorequal.expr_1, 2);
       render("<=");
       pp(_lessthanorequal.expr_2, 2);
       if (_i_ > 1) render(_R_PAREN);
    }
    else     if (foo instanceof stella.Absyn.GreaterThan)
    {
       stella.Absyn.GreaterThan _greaterthan = (stella.Absyn.GreaterThan) foo;
       if (_i_ > 1) render(_L_PAREN);
       pp(_greaterthan.expr_1, 2);
       render(">");
       pp(_greaterthan.expr_2, 2);
       if (_i_ > 1) render(_R_PAREN);
    }
    else     if (foo instanceof stella.Absyn.GreaterThanOrEqual)
    {
       stella.Absyn.GreaterThanOrEqual _greaterthanorequal = (stella.Absyn.GreaterThanOrEqual) foo;
       if (_i_ > 1) render(_L_PAREN);
       pp(_greaterthanorequal.expr_1, 2);
       render(">=");
       pp(_greaterthanorequal.expr_2, 2);
       if (_i_ > 1) render(_R_PAREN);
    }
    else     if (foo instanceof stella.Absyn.Equal)
    {
       stella.Absyn.Equal _equal = (stella.Absyn.Equal) foo;
       if (_i_ > 1) render(_L_PAREN);
       pp(_equal.expr_1, 2);
       render("==");
       pp(_equal.expr_2, 2);
       if (_i_ > 1) render(_R_PAREN);
    }
    else     if (foo instanceof stella.Absyn.NotEqual)
    {
       stella.Absyn.NotEqual _notequal = (stella.Absyn.NotEqual) foo;
       if (_i_ > 1) render(_L_PAREN);
       pp(_notequal.expr_1, 2);
       render("!=");
       pp(_notequal.expr_2, 2);
       if (_i_ > 1) render(_R_PAREN);
    }
    else     if (foo instanceof stella.Absyn.TypeAsc)
    {
       stella.Absyn.TypeAsc _typeasc = (stella.Absyn.TypeAsc) foo;
       if (_i_ > 2) render(_L_PAREN);
       pp(_typeasc.expr_, 2);
       render("as");
       pp(_typeasc.type_, 0);
       if (_i_ > 2) render(_R_PAREN);
    }
    else     if (foo instanceof stella.Absyn.Abstraction)
    {
       stella.Absyn.Abstraction _abstraction = (stella.Absyn.Abstraction) foo;
       if (_i_ > 2) render(_L_PAREN);
       render("fn");
       render("(");
       pp(_abstraction.listparamdecl_, 0);
       render(")");
       render("{");
       render("return");
       pp(_abstraction.expr_, 0);
       render(";");
       render("}");
       if (_i_ > 2) render(_R_PAREN);
    }
    else     if (foo instanceof stella.Absyn.Tuple)
    {
       stella.Absyn.Tuple _tuple = (stella.Absyn.Tuple) foo;
       if (_i_ > 2) render(_L_PAREN);
       render("{");
       pp(_tuple.listexpr_, 0);
       render("}");
       if (_i_ > 2) render(_R_PAREN);
    }
    else     if (foo instanceof stella.Absyn.Record)
    {
       stella.Absyn.Record _record = (stella.Absyn.Record) foo;
       if (_i_ > 2) render(_L_PAREN);
       render("record");
       render("{");
       pp(_record.listbinding_, 0);
       render("}");
       if (_i_ > 2) render(_R_PAREN);
    }
    else     if (foo instanceof stella.Absyn.Variant)
    {
       stella.Absyn.Variant _variant = (stella.Absyn.Variant) foo;
       if (_i_ > 2) render(_L_PAREN);
       render("<|");
       pp(_variant.stellaident_, 0);
       pp(_variant.exprdata_, 0);
       render("|>");
       if (_i_ > 2) render(_R_PAREN);
    }
    else     if (foo instanceof stella.Absyn.Match)
    {
       stella.Absyn.Match _match = (stella.Absyn.Match) foo;
       if (_i_ > 2) render(_L_PAREN);
       render("match");
       pp(_match.expr_, 1);
       render("{");
       pp(_match.listmatchcase_, 0);
       render("}");
       if (_i_ > 2) render(_R_PAREN);
    }
    else     if (foo instanceof stella.Absyn.List)
    {
       stella.Absyn.List _list = (stella.Absyn.List) foo;
       if (_i_ > 2) render(_L_PAREN);
       render("[");
       pp(_list.listexpr_, 0);
       render("]");
       if (_i_ > 2) render(_R_PAREN);
    }
    else     if (foo instanceof stella.Absyn.Add)
    {
       stella.Absyn.Add _add = (stella.Absyn.Add) foo;
       if (_i_ > 2) render(_L_PAREN);
       pp(_add.expr_1, 2);
       render("+");
       pp(_add.expr_2, 3);
       if (_i_ > 2) render(_R_PAREN);
    }
    else     if (foo instanceof stella.Absyn.LogicOr)
    {
       stella.Absyn.LogicOr _logicor = (stella.Absyn.LogicOr) foo;
       if (_i_ > 2) render(_L_PAREN);
       pp(_logicor.expr_1, 2);
       render("or");
       pp(_logicor.expr_2, 3);
       if (_i_ > 2) render(_R_PAREN);
    }
    else     if (foo instanceof stella.Absyn.Multiply)
    {
       stella.Absyn.Multiply _multiply = (stella.Absyn.Multiply) foo;
       if (_i_ > 3) render(_L_PAREN);
       pp(_multiply.expr_1, 3);
       render("*");
       pp(_multiply.expr_2, 4);
       if (_i_ > 3) render(_R_PAREN);
    }
    else     if (foo instanceof stella.Absyn.LogicAnd)
    {
       stella.Absyn.LogicAnd _logicand = (stella.Absyn.LogicAnd) foo;
       if (_i_ > 3) render(_L_PAREN);
       pp(_logicand.expr_1, 3);
       render("and");
       pp(_logicand.expr_2, 4);
       if (_i_ > 3) render(_R_PAREN);
    }
    else     if (foo instanceof stella.Absyn.Application)
    {
       stella.Absyn.Application _application = (stella.Absyn.Application) foo;
       if (_i_ > 4) render(_L_PAREN);
       pp(_application.expr_, 4);
       render("(");
       pp(_application.listexpr_, 0);
       render(")");
       if (_i_ > 4) render(_R_PAREN);
    }
    else     if (foo instanceof stella.Absyn.ConsList)
    {
       stella.Absyn.ConsList _conslist = (stella.Absyn.ConsList) foo;
       if (_i_ > 5) render(_L_PAREN);
       render("cons");
       render("(");
       pp(_conslist.expr_1, 0);
       render(",");
       pp(_conslist.expr_2, 0);
       render(")");
       if (_i_ > 5) render(_R_PAREN);
    }
    else     if (foo instanceof stella.Absyn.Head)
    {
       stella.Absyn.Head _head = (stella.Absyn.Head) foo;
       if (_i_ > 5) render(_L_PAREN);
       render("List::head");
       render("(");
       pp(_head.expr_, 0);
       render(")");
       if (_i_ > 5) render(_R_PAREN);
    }
    else     if (foo instanceof stella.Absyn.IsEmpty)
    {
       stella.Absyn.IsEmpty _isempty = (stella.Absyn.IsEmpty) foo;
       if (_i_ > 5) render(_L_PAREN);
       render("List::isempty");
       render("(");
       pp(_isempty.expr_, 0);
       render(")");
       if (_i_ > 5) render(_R_PAREN);
    }
    else     if (foo instanceof stella.Absyn.Tail)
    {
       stella.Absyn.Tail _tail = (stella.Absyn.Tail) foo;
       if (_i_ > 5) render(_L_PAREN);
       render("List::tail");
       render("(");
       pp(_tail.expr_, 0);
       render(")");
       if (_i_ > 5) render(_R_PAREN);
    }
    else     if (foo instanceof stella.Absyn.Succ)
    {
       stella.Absyn.Succ _succ = (stella.Absyn.Succ) foo;
       if (_i_ > 5) render(_L_PAREN);
       render("succ");
       render("(");
       pp(_succ.expr_, 0);
       render(")");
       if (_i_ > 5) render(_R_PAREN);
    }
    else     if (foo instanceof stella.Absyn.LogicNot)
    {
       stella.Absyn.LogicNot _logicnot = (stella.Absyn.LogicNot) foo;
       if (_i_ > 5) render(_L_PAREN);
       render("not");
       render("(");
       pp(_logicnot.expr_, 0);
       render(")");
       if (_i_ > 5) render(_R_PAREN);
    }
    else     if (foo instanceof stella.Absyn.Pred)
    {
       stella.Absyn.Pred _pred = (stella.Absyn.Pred) foo;
       if (_i_ > 5) render(_L_PAREN);
       render("Nat::pred");
       render("(");
       pp(_pred.expr_, 0);
       render(")");
       if (_i_ > 5) render(_R_PAREN);
    }
    else     if (foo instanceof stella.Absyn.IsZero)
    {
       stella.Absyn.IsZero _iszero = (stella.Absyn.IsZero) foo;
       if (_i_ > 5) render(_L_PAREN);
       render("Nat::iszero");
       render("(");
       pp(_iszero.expr_, 0);
       render(")");
       if (_i_ > 5) render(_R_PAREN);
    }
    else     if (foo instanceof stella.Absyn.Fix)
    {
       stella.Absyn.Fix _fix = (stella.Absyn.Fix) foo;
       if (_i_ > 5) render(_L_PAREN);
       render("fix");
       render("(");
       pp(_fix.expr_, 0);
       render(")");
       if (_i_ > 5) render(_R_PAREN);
    }
    else     if (foo instanceof stella.Absyn.NatRec)
    {
       stella.Absyn.NatRec _natrec = (stella.Absyn.NatRec) foo;
       if (_i_ > 5) render(_L_PAREN);
       render("Nat::rec");
       render("(");
       pp(_natrec.expr_1, 0);
       render(",");
       pp(_natrec.expr_2, 0);
       render(",");
       pp(_natrec.expr_3, 0);
       render(")");
       if (_i_ > 5) render(_R_PAREN);
    }
    else     if (foo instanceof stella.Absyn.Fold)
    {
       stella.Absyn.Fold _fold = (stella.Absyn.Fold) foo;
       if (_i_ > 5) render(_L_PAREN);
       render("fold");
       render("[");
       pp(_fold.type_, 0);
       render("]");
       pp(_fold.expr_, 6);
       if (_i_ > 5) render(_R_PAREN);
    }
    else     if (foo instanceof stella.Absyn.Unfold)
    {
       stella.Absyn.Unfold _unfold = (stella.Absyn.Unfold) foo;
       if (_i_ > 5) render(_L_PAREN);
       render("unfold");
       render("[");
       pp(_unfold.type_, 0);
       render("]");
       pp(_unfold.expr_, 6);
       if (_i_ > 5) render(_R_PAREN);
    }
    else     if (foo instanceof stella.Absyn.DotRecord)
    {
       stella.Absyn.DotRecord _dotrecord = (stella.Absyn.DotRecord) foo;
       if (_i_ > 6) render(_L_PAREN);
       pp(_dotrecord.expr_, 6);
       render(".");
       pp(_dotrecord.stellaident_, 0);
       if (_i_ > 6) render(_R_PAREN);
    }
    else     if (foo instanceof stella.Absyn.DotTuple)
    {
       stella.Absyn.DotTuple _dottuple = (stella.Absyn.DotTuple) foo;
       if (_i_ > 6) render(_L_PAREN);
       pp(_dottuple.expr_, 6);
       render(".");
       pp(_dottuple.integer_, 0);
       if (_i_ > 6) render(_R_PAREN);
    }
    else     if (foo instanceof stella.Absyn.ConstTrue)
    {
       stella.Absyn.ConstTrue _consttrue = (stella.Absyn.ConstTrue) foo;
       if (_i_ > 6) render(_L_PAREN);
       render("true");
       if (_i_ > 6) render(_R_PAREN);
    }
    else     if (foo instanceof stella.Absyn.ConstFalse)
    {
       stella.Absyn.ConstFalse _constfalse = (stella.Absyn.ConstFalse) foo;
       if (_i_ > 6) render(_L_PAREN);
       render("false");
       if (_i_ > 6) render(_R_PAREN);
    }
    else     if (foo instanceof stella.Absyn.ConstInt)
    {
       stella.Absyn.ConstInt _constint = (stella.Absyn.ConstInt) foo;
       if (_i_ > 6) render(_L_PAREN);
       pp(_constint.integer_, 0);
       if (_i_ > 6) render(_R_PAREN);
    }
    else     if (foo instanceof stella.Absyn.Var)
    {
       stella.Absyn.Var _var = (stella.Absyn.Var) foo;
       if (_i_ > 6) render(_L_PAREN);
       pp(_var.stellaident_, 0);
       if (_i_ > 6) render(_R_PAREN);
    }

  }

  private static void pp(stella.Absyn.ListExpr foo, int _i_)
  {
    ppListExpr(foo.iterator(), _i_);
  }

  private static void ppListExpr(java.util.Iterator<stella.Absyn.Expr> it, int _i_)
  {
    if (it.hasNext())
    {
      stella.Absyn.Expr el = it.next();
      if (!it.hasNext())
      { /* last */
        pp(el, _i_);
      }
      else
      { /* cons */
        pp(el, _i_); render(","); ppListExpr(it, _i_);
      }
    }
  }


  private static void pp(stella.Absyn.MatchCase foo, int _i_)
  {
    if (foo instanceof stella.Absyn.AMatchCase)
    {
       stella.Absyn.AMatchCase _amatchcase = (stella.Absyn.AMatchCase) foo;
       if (_i_ > 0) render(_L_PAREN);
       pp(_amatchcase.pattern_, 0);
       render("=>");
       pp(_amatchcase.expr_, 0);
       if (_i_ > 0) render(_R_PAREN);
    }

  }

  private static void pp(stella.Absyn.ListMatchCase foo, int _i_)
  {
    ppListMatchCase(foo.iterator(), _i_);
  }

  private static void ppListMatchCase(java.util.Iterator<stella.Absyn.MatchCase> it, int _i_)
  {
    if (it.hasNext())
    {
      stella.Absyn.MatchCase el = it.next();
      if (!it.hasNext())
      { /* last */
        pp(el, _i_);
      }
      else
      { /* cons */
        pp(el, _i_); render(";"); ppListMatchCase(it, _i_);
      }
    }
  }


  private static void pp(stella.Absyn.OptionalTyping foo, int _i_)
  {
    if (foo instanceof stella.Absyn.NoTyping)
    {
       stella.Absyn.NoTyping _notyping = (stella.Absyn.NoTyping) foo;
       if (_i_ > 0) render(_L_PAREN);
       if (_i_ > 0) render(_R_PAREN);
    }
    else     if (foo instanceof stella.Absyn.SomeTyping)
    {
       stella.Absyn.SomeTyping _sometyping = (stella.Absyn.SomeTyping) foo;
       if (_i_ > 0) render(_L_PAREN);
       render(":");
       pp(_sometyping.type_, 0);
       if (_i_ > 0) render(_R_PAREN);
    }

  }

  private static void pp(stella.Absyn.PatternData foo, int _i_)
  {
    if (foo instanceof stella.Absyn.NoPatternData)
    {
       stella.Absyn.NoPatternData _nopatterndata = (stella.Absyn.NoPatternData) foo;
       if (_i_ > 0) render(_L_PAREN);
       if (_i_ > 0) render(_R_PAREN);
    }
    else     if (foo instanceof stella.Absyn.SomePatternData)
    {
       stella.Absyn.SomePatternData _somepatterndata = (stella.Absyn.SomePatternData) foo;
       if (_i_ > 0) render(_L_PAREN);
       render("=");
       pp(_somepatterndata.pattern_, 0);
       if (_i_ > 0) render(_R_PAREN);
    }

  }

  private static void pp(stella.Absyn.ExprData foo, int _i_)
  {
    if (foo instanceof stella.Absyn.NoExprData)
    {
       stella.Absyn.NoExprData _noexprdata = (stella.Absyn.NoExprData) foo;
       if (_i_ > 0) render(_L_PAREN);
       if (_i_ > 0) render(_R_PAREN);
    }
    else     if (foo instanceof stella.Absyn.SomeExprData)
    {
       stella.Absyn.SomeExprData _someexprdata = (stella.Absyn.SomeExprData) foo;
       if (_i_ > 0) render(_L_PAREN);
       render("=");
       pp(_someexprdata.expr_, 0);
       if (_i_ > 0) render(_R_PAREN);
    }

  }

  private static void pp(stella.Absyn.Pattern foo, int _i_)
  {
    if (foo instanceof stella.Absyn.PatternVariant)
    {
       stella.Absyn.PatternVariant _patternvariant = (stella.Absyn.PatternVariant) foo;
       if (_i_ > 0) render(_L_PAREN);
       render("<|");
       pp(_patternvariant.stellaident_, 0);
       pp(_patternvariant.patterndata_, 0);
       render("|>");
       if (_i_ > 0) render(_R_PAREN);
    }
    else     if (foo instanceof stella.Absyn.PatternTuple)
    {
       stella.Absyn.PatternTuple _patterntuple = (stella.Absyn.PatternTuple) foo;
       if (_i_ > 0) render(_L_PAREN);
       render("{");
       pp(_patterntuple.listpattern_, 0);
       render("}");
       if (_i_ > 0) render(_R_PAREN);
    }
    else     if (foo instanceof stella.Absyn.PatternRecord)
    {
       stella.Absyn.PatternRecord _patternrecord = (stella.Absyn.PatternRecord) foo;
       if (_i_ > 0) render(_L_PAREN);
       render("record");
       render("{");
       pp(_patternrecord.listlabelledpattern_, 0);
       render("}");
       if (_i_ > 0) render(_R_PAREN);
    }
    else     if (foo instanceof stella.Absyn.PatternList)
    {
       stella.Absyn.PatternList _patternlist = (stella.Absyn.PatternList) foo;
       if (_i_ > 0) render(_L_PAREN);
       render("[");
       pp(_patternlist.listpattern_, 0);
       render("]");
       if (_i_ > 0) render(_R_PAREN);
    }
    else     if (foo instanceof stella.Absyn.PatternCons)
    {
       stella.Absyn.PatternCons _patterncons = (stella.Absyn.PatternCons) foo;
       if (_i_ > 0) render(_L_PAREN);
       render("cons");
       render("(");
       pp(_patterncons.pattern_1, 0);
       render(",");
       pp(_patterncons.pattern_2, 0);
       render(")");
       if (_i_ > 0) render(_R_PAREN);
    }
    else     if (foo instanceof stella.Absyn.PatternFalse)
    {
       stella.Absyn.PatternFalse _patternfalse = (stella.Absyn.PatternFalse) foo;
       if (_i_ > 0) render(_L_PAREN);
       render("false");
       if (_i_ > 0) render(_R_PAREN);
    }
    else     if (foo instanceof stella.Absyn.PatternTrue)
    {
       stella.Absyn.PatternTrue _patterntrue = (stella.Absyn.PatternTrue) foo;
       if (_i_ > 0) render(_L_PAREN);
       render("true");
       if (_i_ > 0) render(_R_PAREN);
    }
    else     if (foo instanceof stella.Absyn.PatternInt)
    {
       stella.Absyn.PatternInt _patternint = (stella.Absyn.PatternInt) foo;
       if (_i_ > 0) render(_L_PAREN);
       pp(_patternint.integer_, 0);
       if (_i_ > 0) render(_R_PAREN);
    }
    else     if (foo instanceof stella.Absyn.PatternSucc)
    {
       stella.Absyn.PatternSucc _patternsucc = (stella.Absyn.PatternSucc) foo;
       if (_i_ > 0) render(_L_PAREN);
       render("succ");
       render("(");
       pp(_patternsucc.pattern_, 0);
       render(")");
       if (_i_ > 0) render(_R_PAREN);
    }
    else     if (foo instanceof stella.Absyn.PatternVar)
    {
       stella.Absyn.PatternVar _patternvar = (stella.Absyn.PatternVar) foo;
       if (_i_ > 0) render(_L_PAREN);
       pp(_patternvar.stellaident_, 0);
       if (_i_ > 0) render(_R_PAREN);
    }

  }

  private static void pp(stella.Absyn.ListPattern foo, int _i_)
  {
    ppListPattern(foo.iterator(), _i_);
  }

  private static void ppListPattern(java.util.Iterator<stella.Absyn.Pattern> it, int _i_)
  {
    if (it.hasNext())
    {
      stella.Absyn.Pattern el = it.next();
      if (!it.hasNext())
      { /* last */
        pp(el, _i_);
      }
      else
      { /* cons */
        pp(el, _i_); render(","); ppListPattern(it, _i_);
      }
    }
  }


  private static void pp(stella.Absyn.LabelledPattern foo, int _i_)
  {
    if (foo instanceof stella.Absyn.ALabelledPattern)
    {
       stella.Absyn.ALabelledPattern _alabelledpattern = (stella.Absyn.ALabelledPattern) foo;
       if (_i_ > 0) render(_L_PAREN);
       pp(_alabelledpattern.stellaident_, 0);
       render("=");
       pp(_alabelledpattern.pattern_, 0);
       if (_i_ > 0) render(_R_PAREN);
    }

  }

  private static void pp(stella.Absyn.ListLabelledPattern foo, int _i_)
  {
    ppListLabelledPattern(foo.iterator(), _i_);
  }

  private static void ppListLabelledPattern(java.util.Iterator<stella.Absyn.LabelledPattern> it, int _i_)
  {
    if (it.hasNext())
    {
      stella.Absyn.LabelledPattern el = it.next();
      if (!it.hasNext())
      { /* last */
        pp(el, _i_);
      }
      else
      { /* cons */
        pp(el, _i_); render(","); ppListLabelledPattern(it, _i_);
      }
    }
  }


  private static void pp(stella.Absyn.Binding foo, int _i_)
  {
    if (foo instanceof stella.Absyn.ABinding)
    {
       stella.Absyn.ABinding _abinding = (stella.Absyn.ABinding) foo;
       if (_i_ > 0) render(_L_PAREN);
       pp(_abinding.stellaident_, 0);
       render("=");
       pp(_abinding.expr_, 0);
       if (_i_ > 0) render(_R_PAREN);
    }

  }

  private static void pp(stella.Absyn.ListBinding foo, int _i_)
  {
    ppListBinding(foo.iterator(), _i_);
  }

  private static void ppListBinding(java.util.Iterator<stella.Absyn.Binding> it, int _i_)
  {
    if (it.hasNext())
    {
      stella.Absyn.Binding el = it.next();
      if (!it.hasNext())
      { /* last */
        pp(el, _i_);
      }
      else
      { /* cons */
        pp(el, _i_); render(","); ppListBinding(it, _i_);
      }
    }
  }


  private static void pp(stella.Absyn.Type foo, int _i_)
  {
    if (foo instanceof stella.Absyn.TypeFun)
    {
       stella.Absyn.TypeFun _typefun = (stella.Absyn.TypeFun) foo;
       if (_i_ > 0) render(_L_PAREN);
       render("fn");
       render("(");
       pp(_typefun.listtype_, 0);
       render(")");
       render("->");
       pp(_typefun.type_, 0);
       if (_i_ > 0) render(_R_PAREN);
    }
    else     if (foo instanceof stella.Absyn.TypeRec)
    {
       stella.Absyn.TypeRec _typerec = (stella.Absyn.TypeRec) foo;
       if (_i_ > 0) render(_L_PAREN);
       render("µ");
       pp(_typerec.stellaident_, 0);
       render(".");
       pp(_typerec.type_, 0);
       if (_i_ > 0) render(_R_PAREN);
    }
    else     if (foo instanceof stella.Absyn.TypeSum)
    {
       stella.Absyn.TypeSum _typesum = (stella.Absyn.TypeSum) foo;
       if (_i_ > 1) render(_L_PAREN);
       pp(_typesum.type_1, 2);
       render("+");
       pp(_typesum.type_2, 2);
       if (_i_ > 1) render(_R_PAREN);
    }
    else     if (foo instanceof stella.Absyn.TypeTuple)
    {
       stella.Absyn.TypeTuple _typetuple = (stella.Absyn.TypeTuple) foo;
       if (_i_ > 2) render(_L_PAREN);
       render("{");
       pp(_typetuple.listtype_, 0);
       render("}");
       if (_i_ > 2) render(_R_PAREN);
    }
    else     if (foo instanceof stella.Absyn.TypeRecord)
    {
       stella.Absyn.TypeRecord _typerecord = (stella.Absyn.TypeRecord) foo;
       if (_i_ > 2) render(_L_PAREN);
       render("record");
       render("{");
       pp(_typerecord.listrecordfieldtype_, 0);
       render("}");
       if (_i_ > 2) render(_R_PAREN);
    }
    else     if (foo instanceof stella.Absyn.TypeVariant)
    {
       stella.Absyn.TypeVariant _typevariant = (stella.Absyn.TypeVariant) foo;
       if (_i_ > 2) render(_L_PAREN);
       render("variant");
       render("<|");
       pp(_typevariant.listvariantfieldtype_, 0);
       render("|>");
       if (_i_ > 2) render(_R_PAREN);
    }
    else     if (foo instanceof stella.Absyn.TypeList)
    {
       stella.Absyn.TypeList _typelist = (stella.Absyn.TypeList) foo;
       if (_i_ > 2) render(_L_PAREN);
       render("[");
       pp(_typelist.type_, 0);
       render("]");
       if (_i_ > 2) render(_R_PAREN);
    }
    else     if (foo instanceof stella.Absyn.TypeBool)
    {
       stella.Absyn.TypeBool _typebool = (stella.Absyn.TypeBool) foo;
       if (_i_ > 3) render(_L_PAREN);
       render("Bool");
       if (_i_ > 3) render(_R_PAREN);
    }
    else     if (foo instanceof stella.Absyn.TypeNat)
    {
       stella.Absyn.TypeNat _typenat = (stella.Absyn.TypeNat) foo;
       if (_i_ > 3) render(_L_PAREN);
       render("Nat");
       if (_i_ > 3) render(_R_PAREN);
    }
    else     if (foo instanceof stella.Absyn.TypeUnit)
    {
       stella.Absyn.TypeUnit _typeunit = (stella.Absyn.TypeUnit) foo;
       if (_i_ > 3) render(_L_PAREN);
       render("Unit");
       if (_i_ > 3) render(_R_PAREN);
    }
    else     if (foo instanceof stella.Absyn.TypeVar)
    {
       stella.Absyn.TypeVar _typevar = (stella.Absyn.TypeVar) foo;
       if (_i_ > 3) render(_L_PAREN);
       pp(_typevar.stellaident_, 0);
       if (_i_ > 3) render(_R_PAREN);
    }

  }

  private static void pp(stella.Absyn.ListType foo, int _i_)
  {
    ppListType(foo.iterator(), _i_);
  }

  private static void ppListType(java.util.Iterator<stella.Absyn.Type> it, int _i_)
  {
    if (it.hasNext())
    {
      stella.Absyn.Type el = it.next();
      if (!it.hasNext())
      { /* last */
        pp(el, _i_);
      }
      else
      { /* cons */
        pp(el, _i_); render(","); ppListType(it, _i_);
      }
    }
  }


  private static void pp(stella.Absyn.VariantFieldType foo, int _i_)
  {
    if (foo instanceof stella.Absyn.AVariantFieldType)
    {
       stella.Absyn.AVariantFieldType _avariantfieldtype = (stella.Absyn.AVariantFieldType) foo;
       if (_i_ > 0) render(_L_PAREN);
       pp(_avariantfieldtype.stellaident_, 0);
       pp(_avariantfieldtype.optionaltyping_, 0);
       if (_i_ > 0) render(_R_PAREN);
    }

  }

  private static void pp(stella.Absyn.ListVariantFieldType foo, int _i_)
  {
    ppListVariantFieldType(foo.iterator(), _i_);
  }

  private static void ppListVariantFieldType(java.util.Iterator<stella.Absyn.VariantFieldType> it, int _i_)
  {
    if (it.hasNext())
    {
      stella.Absyn.VariantFieldType el = it.next();
      if (!it.hasNext())
      { /* last */
        pp(el, _i_);
      }
      else
      { /* cons */
        pp(el, _i_); render(","); ppListVariantFieldType(it, _i_);
      }
    }
  }


  private static void pp(stella.Absyn.RecordFieldType foo, int _i_)
  {
    if (foo instanceof stella.Absyn.ARecordFieldType)
    {
       stella.Absyn.ARecordFieldType _arecordfieldtype = (stella.Absyn.ARecordFieldType) foo;
       if (_i_ > 0) render(_L_PAREN);
       pp(_arecordfieldtype.stellaident_, 0);
       render(":");
       pp(_arecordfieldtype.type_, 0);
       if (_i_ > 0) render(_R_PAREN);
    }

  }

  private static void pp(stella.Absyn.ListRecordFieldType foo, int _i_)
  {
    ppListRecordFieldType(foo.iterator(), _i_);
  }

  private static void ppListRecordFieldType(java.util.Iterator<stella.Absyn.RecordFieldType> it, int _i_)
  {
    if (it.hasNext())
    {
      stella.Absyn.RecordFieldType el = it.next();
      if (!it.hasNext())
      { /* last */
        pp(el, _i_);
      }
      else
      { /* cons */
        pp(el, _i_); render(","); ppListRecordFieldType(it, _i_);
      }
    }
  }


  private static void pp(stella.Absyn.Typing foo, int _i_)
  {
    if (foo instanceof stella.Absyn.ATyping)
    {
       stella.Absyn.ATyping _atyping = (stella.Absyn.ATyping) foo;
       if (_i_ > 0) render(_L_PAREN);
       pp(_atyping.expr_, 0);
       render(":");
       pp(_atyping.type_, 0);
       if (_i_ > 0) render(_R_PAREN);
    }

  }


  private static void sh(stella.Absyn.ListStellaIdent foo)
  {
     for (java.util.Iterator<String> it = foo.iterator(); it.hasNext();)
     {
       sh(it.next());
       if (it.hasNext())
         render(",");
     }
  }

  private static void sh(stella.Absyn.Program foo)
  {
    if (foo instanceof stella.Absyn.AProgram)
    {
       stella.Absyn.AProgram _aprogram = (stella.Absyn.AProgram) foo;
       render("(");
       render("AProgram");
       sh(_aprogram.languagedecl_);
       render("[");
       sh(_aprogram.listextension_);
       render("]");
       render("[");
       sh(_aprogram.listdecl_);
       render("]");
       render(")");
    }
  }

  private static void sh(stella.Absyn.LanguageDecl foo)
  {
    if (foo instanceof stella.Absyn.LanguageCore)
    {
       stella.Absyn.LanguageCore _languagecore = (stella.Absyn.LanguageCore) foo;
       render("LanguageCore");
    }
  }

  private static void sh(stella.Absyn.Extension foo)
  {
    if (foo instanceof stella.Absyn.AnExtension)
    {
       stella.Absyn.AnExtension _anextension = (stella.Absyn.AnExtension) foo;
       render("(");
       render("AnExtension");
       render("[");
       sh(_anextension.listextensionname_);
       render("]");
       render(")");
    }
  }

  private static void sh(stella.Absyn.ListExtensionName foo)
  {
     for (java.util.Iterator<String> it = foo.iterator(); it.hasNext();)
     {
       sh(it.next());
       if (it.hasNext())
         render(",");
     }
  }

  private static void sh(stella.Absyn.ListExtension foo)
  {
     for (java.util.Iterator<stella.Absyn.Extension> it = foo.iterator(); it.hasNext();)
     {
       sh(it.next());
       if (it.hasNext())
         render(",");
     }
  }

  private static void sh(stella.Absyn.Decl foo)
  {
    if (foo instanceof stella.Absyn.DeclFun)
    {
       stella.Absyn.DeclFun _declfun = (stella.Absyn.DeclFun) foo;
       render("(");
       render("DeclFun");
       render("[");
       sh(_declfun.listannotation_);
       render("]");
       sh(_declfun.stellaident_);
       render("[");
       sh(_declfun.listparamdecl_);
       render("]");
       sh(_declfun.returntype_);
       sh(_declfun.throwtype_);
       render("[");
       sh(_declfun.listdecl_);
       render("]");
       sh(_declfun.expr_);
       render(")");
    }
    if (foo instanceof stella.Absyn.DeclTypeAlias)
    {
       stella.Absyn.DeclTypeAlias _decltypealias = (stella.Absyn.DeclTypeAlias) foo;
       render("(");
       render("DeclTypeAlias");
       sh(_decltypealias.stellaident_);
       sh(_decltypealias.type_);
       render(")");
    }
  }

  private static void sh(stella.Absyn.ListDecl foo)
  {
     for (java.util.Iterator<stella.Absyn.Decl> it = foo.iterator(); it.hasNext();)
     {
       sh(it.next());
       if (it.hasNext())
         render(",");
     }
  }

  private static void sh(stella.Absyn.LocalDecl foo)
  {
    if (foo instanceof stella.Absyn.ALocalDecl)
    {
       stella.Absyn.ALocalDecl _alocaldecl = (stella.Absyn.ALocalDecl) foo;
       render("(");
       render("ALocalDecl");
       sh(_alocaldecl.decl_);
       render(")");
    }
  }

  private static void sh(stella.Absyn.ListLocalDecl foo)
  {
     for (java.util.Iterator<stella.Absyn.LocalDecl> it = foo.iterator(); it.hasNext();)
     {
       sh(it.next());
       if (it.hasNext())
         render(",");
     }
  }

  private static void sh(stella.Absyn.Annotation foo)
  {
    if (foo instanceof stella.Absyn.InlineAnnotation)
    {
       stella.Absyn.InlineAnnotation _inlineannotation = (stella.Absyn.InlineAnnotation) foo;
       render("InlineAnnotation");
    }
  }

  private static void sh(stella.Absyn.ListAnnotation foo)
  {
     for (java.util.Iterator<stella.Absyn.Annotation> it = foo.iterator(); it.hasNext();)
     {
       sh(it.next());
       if (it.hasNext())
         render(",");
     }
  }

  private static void sh(stella.Absyn.ParamDecl foo)
  {
    if (foo instanceof stella.Absyn.AParamDecl)
    {
       stella.Absyn.AParamDecl _aparamdecl = (stella.Absyn.AParamDecl) foo;
       render("(");
       render("AParamDecl");
       sh(_aparamdecl.stellaident_);
       sh(_aparamdecl.type_);
       render(")");
    }
  }

  private static void sh(stella.Absyn.ListParamDecl foo)
  {
     for (java.util.Iterator<stella.Absyn.ParamDecl> it = foo.iterator(); it.hasNext();)
     {
       sh(it.next());
       if (it.hasNext())
         render(",");
     }
  }

  private static void sh(stella.Absyn.ReturnType foo)
  {
    if (foo instanceof stella.Absyn.NoReturnType)
    {
       stella.Absyn.NoReturnType _noreturntype = (stella.Absyn.NoReturnType) foo;
       render("NoReturnType");
    }
    if (foo instanceof stella.Absyn.SomeReturnType)
    {
       stella.Absyn.SomeReturnType _somereturntype = (stella.Absyn.SomeReturnType) foo;
       render("(");
       render("SomeReturnType");
       sh(_somereturntype.type_);
       render(")");
    }
  }

  private static void sh(stella.Absyn.ThrowType foo)
  {
    if (foo instanceof stella.Absyn.NoThrowType)
    {
       stella.Absyn.NoThrowType _nothrowtype = (stella.Absyn.NoThrowType) foo;
       render("NoThrowType");
    }
    if (foo instanceof stella.Absyn.SomeThrowType)
    {
       stella.Absyn.SomeThrowType _somethrowtype = (stella.Absyn.SomeThrowType) foo;
       render("(");
       render("SomeThrowType");
       render("[");
       sh(_somethrowtype.listtype_);
       render("]");
       render(")");
    }
  }

  private static void sh(stella.Absyn.Expr foo)
  {
    if (foo instanceof stella.Absyn.If)
    {
       stella.Absyn.If _if = (stella.Absyn.If) foo;
       render("(");
       render("If");
       sh(_if.expr_1);
       sh(_if.expr_2);
       sh(_if.expr_3);
       render(")");
    }
    if (foo instanceof stella.Absyn.Let)
    {
       stella.Absyn.Let _let = (stella.Absyn.Let) foo;
       render("(");
       render("Let");
       sh(_let.stellaident_);
       sh(_let.expr_1);
       sh(_let.expr_2);
       render(")");
    }
    if (foo instanceof stella.Absyn.LessThan)
    {
       stella.Absyn.LessThan _lessthan = (stella.Absyn.LessThan) foo;
       render("(");
       render("LessThan");
       sh(_lessthan.expr_1);
       sh(_lessthan.expr_2);
       render(")");
    }
    if (foo instanceof stella.Absyn.LessThanOrEqual)
    {
       stella.Absyn.LessThanOrEqual _lessthanorequal = (stella.Absyn.LessThanOrEqual) foo;
       render("(");
       render("LessThanOrEqual");
       sh(_lessthanorequal.expr_1);
       sh(_lessthanorequal.expr_2);
       render(")");
    }
    if (foo instanceof stella.Absyn.GreaterThan)
    {
       stella.Absyn.GreaterThan _greaterthan = (stella.Absyn.GreaterThan) foo;
       render("(");
       render("GreaterThan");
       sh(_greaterthan.expr_1);
       sh(_greaterthan.expr_2);
       render(")");
    }
    if (foo instanceof stella.Absyn.GreaterThanOrEqual)
    {
       stella.Absyn.GreaterThanOrEqual _greaterthanorequal = (stella.Absyn.GreaterThanOrEqual) foo;
       render("(");
       render("GreaterThanOrEqual");
       sh(_greaterthanorequal.expr_1);
       sh(_greaterthanorequal.expr_2);
       render(")");
    }
    if (foo instanceof stella.Absyn.Equal)
    {
       stella.Absyn.Equal _equal = (stella.Absyn.Equal) foo;
       render("(");
       render("Equal");
       sh(_equal.expr_1);
       sh(_equal.expr_2);
       render(")");
    }
    if (foo instanceof stella.Absyn.NotEqual)
    {
       stella.Absyn.NotEqual _notequal = (stella.Absyn.NotEqual) foo;
       render("(");
       render("NotEqual");
       sh(_notequal.expr_1);
       sh(_notequal.expr_2);
       render(")");
    }
    if (foo instanceof stella.Absyn.TypeAsc)
    {
       stella.Absyn.TypeAsc _typeasc = (stella.Absyn.TypeAsc) foo;
       render("(");
       render("TypeAsc");
       sh(_typeasc.expr_);
       sh(_typeasc.type_);
       render(")");
    }
    if (foo instanceof stella.Absyn.Abstraction)
    {
       stella.Absyn.Abstraction _abstraction = (stella.Absyn.Abstraction) foo;
       render("(");
       render("Abstraction");
       render("[");
       sh(_abstraction.listparamdecl_);
       render("]");
       sh(_abstraction.expr_);
       render(")");
    }
    if (foo instanceof stella.Absyn.Tuple)
    {
       stella.Absyn.Tuple _tuple = (stella.Absyn.Tuple) foo;
       render("(");
       render("Tuple");
       render("[");
       sh(_tuple.listexpr_);
       render("]");
       render(")");
    }
    if (foo instanceof stella.Absyn.Record)
    {
       stella.Absyn.Record _record = (stella.Absyn.Record) foo;
       render("(");
       render("Record");
       render("[");
       sh(_record.listbinding_);
       render("]");
       render(")");
    }
    if (foo instanceof stella.Absyn.Variant)
    {
       stella.Absyn.Variant _variant = (stella.Absyn.Variant) foo;
       render("(");
       render("Variant");
       sh(_variant.stellaident_);
       sh(_variant.exprdata_);
       render(")");
    }
    if (foo instanceof stella.Absyn.Match)
    {
       stella.Absyn.Match _match = (stella.Absyn.Match) foo;
       render("(");
       render("Match");
       sh(_match.expr_);
       render("[");
       sh(_match.listmatchcase_);
       render("]");
       render(")");
    }
    if (foo instanceof stella.Absyn.List)
    {
       stella.Absyn.List _list = (stella.Absyn.List) foo;
       render("(");
       render("List");
       render("[");
       sh(_list.listexpr_);
       render("]");
       render(")");
    }
    if (foo instanceof stella.Absyn.Add)
    {
       stella.Absyn.Add _add = (stella.Absyn.Add) foo;
       render("(");
       render("Add");
       sh(_add.expr_1);
       sh(_add.expr_2);
       render(")");
    }
    if (foo instanceof stella.Absyn.LogicOr)
    {
       stella.Absyn.LogicOr _logicor = (stella.Absyn.LogicOr) foo;
       render("(");
       render("LogicOr");
       sh(_logicor.expr_1);
       sh(_logicor.expr_2);
       render(")");
    }
    if (foo instanceof stella.Absyn.Multiply)
    {
       stella.Absyn.Multiply _multiply = (stella.Absyn.Multiply) foo;
       render("(");
       render("Multiply");
       sh(_multiply.expr_1);
       sh(_multiply.expr_2);
       render(")");
    }
    if (foo instanceof stella.Absyn.LogicAnd)
    {
       stella.Absyn.LogicAnd _logicand = (stella.Absyn.LogicAnd) foo;
       render("(");
       render("LogicAnd");
       sh(_logicand.expr_1);
       sh(_logicand.expr_2);
       render(")");
    }
    if (foo instanceof stella.Absyn.Application)
    {
       stella.Absyn.Application _application = (stella.Absyn.Application) foo;
       render("(");
       render("Application");
       sh(_application.expr_);
       render("[");
       sh(_application.listexpr_);
       render("]");
       render(")");
    }
    if (foo instanceof stella.Absyn.ConsList)
    {
       stella.Absyn.ConsList _conslist = (stella.Absyn.ConsList) foo;
       render("(");
       render("ConsList");
       sh(_conslist.expr_1);
       sh(_conslist.expr_2);
       render(")");
    }
    if (foo instanceof stella.Absyn.Head)
    {
       stella.Absyn.Head _head = (stella.Absyn.Head) foo;
       render("(");
       render("Head");
       sh(_head.expr_);
       render(")");
    }
    if (foo instanceof stella.Absyn.IsEmpty)
    {
       stella.Absyn.IsEmpty _isempty = (stella.Absyn.IsEmpty) foo;
       render("(");
       render("IsEmpty");
       sh(_isempty.expr_);
       render(")");
    }
    if (foo instanceof stella.Absyn.Tail)
    {
       stella.Absyn.Tail _tail = (stella.Absyn.Tail) foo;
       render("(");
       render("Tail");
       sh(_tail.expr_);
       render(")");
    }
    if (foo instanceof stella.Absyn.Succ)
    {
       stella.Absyn.Succ _succ = (stella.Absyn.Succ) foo;
       render("(");
       render("Succ");
       sh(_succ.expr_);
       render(")");
    }
    if (foo instanceof stella.Absyn.LogicNot)
    {
       stella.Absyn.LogicNot _logicnot = (stella.Absyn.LogicNot) foo;
       render("(");
       render("LogicNot");
       sh(_logicnot.expr_);
       render(")");
    }
    if (foo instanceof stella.Absyn.Pred)
    {
       stella.Absyn.Pred _pred = (stella.Absyn.Pred) foo;
       render("(");
       render("Pred");
       sh(_pred.expr_);
       render(")");
    }
    if (foo instanceof stella.Absyn.IsZero)
    {
       stella.Absyn.IsZero _iszero = (stella.Absyn.IsZero) foo;
       render("(");
       render("IsZero");
       sh(_iszero.expr_);
       render(")");
    }
    if (foo instanceof stella.Absyn.Fix)
    {
       stella.Absyn.Fix _fix = (stella.Absyn.Fix) foo;
       render("(");
       render("Fix");
       sh(_fix.expr_);
       render(")");
    }
    if (foo instanceof stella.Absyn.NatRec)
    {
       stella.Absyn.NatRec _natrec = (stella.Absyn.NatRec) foo;
       render("(");
       render("NatRec");
       sh(_natrec.expr_1);
       sh(_natrec.expr_2);
       sh(_natrec.expr_3);
       render(")");
    }
    if (foo instanceof stella.Absyn.Fold)
    {
       stella.Absyn.Fold _fold = (stella.Absyn.Fold) foo;
       render("(");
       render("Fold");
       sh(_fold.type_);
       sh(_fold.expr_);
       render(")");
    }
    if (foo instanceof stella.Absyn.Unfold)
    {
       stella.Absyn.Unfold _unfold = (stella.Absyn.Unfold) foo;
       render("(");
       render("Unfold");
       sh(_unfold.type_);
       sh(_unfold.expr_);
       render(")");
    }
    if (foo instanceof stella.Absyn.DotRecord)
    {
       stella.Absyn.DotRecord _dotrecord = (stella.Absyn.DotRecord) foo;
       render("(");
       render("DotRecord");
       sh(_dotrecord.expr_);
       sh(_dotrecord.stellaident_);
       render(")");
    }
    if (foo instanceof stella.Absyn.DotTuple)
    {
       stella.Absyn.DotTuple _dottuple = (stella.Absyn.DotTuple) foo;
       render("(");
       render("DotTuple");
       sh(_dottuple.expr_);
       sh(_dottuple.integer_);
       render(")");
    }
    if (foo instanceof stella.Absyn.ConstTrue)
    {
       stella.Absyn.ConstTrue _consttrue = (stella.Absyn.ConstTrue) foo;
       render("ConstTrue");
    }
    if (foo instanceof stella.Absyn.ConstFalse)
    {
       stella.Absyn.ConstFalse _constfalse = (stella.Absyn.ConstFalse) foo;
       render("ConstFalse");
    }
    if (foo instanceof stella.Absyn.ConstInt)
    {
       stella.Absyn.ConstInt _constint = (stella.Absyn.ConstInt) foo;
       render("(");
       render("ConstInt");
       sh(_constint.integer_);
       render(")");
    }
    if (foo instanceof stella.Absyn.Var)
    {
       stella.Absyn.Var _var = (stella.Absyn.Var) foo;
       render("(");
       render("Var");
       sh(_var.stellaident_);
       render(")");
    }
  }

  private static void sh(stella.Absyn.ListExpr foo)
  {
     for (java.util.Iterator<stella.Absyn.Expr> it = foo.iterator(); it.hasNext();)
     {
       sh(it.next());
       if (it.hasNext())
         render(",");
     }
  }

  private static void sh(stella.Absyn.MatchCase foo)
  {
    if (foo instanceof stella.Absyn.AMatchCase)
    {
       stella.Absyn.AMatchCase _amatchcase = (stella.Absyn.AMatchCase) foo;
       render("(");
       render("AMatchCase");
       sh(_amatchcase.pattern_);
       sh(_amatchcase.expr_);
       render(")");
    }
  }

  private static void sh(stella.Absyn.ListMatchCase foo)
  {
     for (java.util.Iterator<stella.Absyn.MatchCase> it = foo.iterator(); it.hasNext();)
     {
       sh(it.next());
       if (it.hasNext())
         render(",");
     }
  }

  private static void sh(stella.Absyn.OptionalTyping foo)
  {
    if (foo instanceof stella.Absyn.NoTyping)
    {
       stella.Absyn.NoTyping _notyping = (stella.Absyn.NoTyping) foo;
       render("NoTyping");
    }
    if (foo instanceof stella.Absyn.SomeTyping)
    {
       stella.Absyn.SomeTyping _sometyping = (stella.Absyn.SomeTyping) foo;
       render("(");
       render("SomeTyping");
       sh(_sometyping.type_);
       render(")");
    }
  }

  private static void sh(stella.Absyn.PatternData foo)
  {
    if (foo instanceof stella.Absyn.NoPatternData)
    {
       stella.Absyn.NoPatternData _nopatterndata = (stella.Absyn.NoPatternData) foo;
       render("NoPatternData");
    }
    if (foo instanceof stella.Absyn.SomePatternData)
    {
       stella.Absyn.SomePatternData _somepatterndata = (stella.Absyn.SomePatternData) foo;
       render("(");
       render("SomePatternData");
       sh(_somepatterndata.pattern_);
       render(")");
    }
  }

  private static void sh(stella.Absyn.ExprData foo)
  {
    if (foo instanceof stella.Absyn.NoExprData)
    {
       stella.Absyn.NoExprData _noexprdata = (stella.Absyn.NoExprData) foo;
       render("NoExprData");
    }
    if (foo instanceof stella.Absyn.SomeExprData)
    {
       stella.Absyn.SomeExprData _someexprdata = (stella.Absyn.SomeExprData) foo;
       render("(");
       render("SomeExprData");
       sh(_someexprdata.expr_);
       render(")");
    }
  }

  private static void sh(stella.Absyn.Pattern foo)
  {
    if (foo instanceof stella.Absyn.PatternVariant)
    {
       stella.Absyn.PatternVariant _patternvariant = (stella.Absyn.PatternVariant) foo;
       render("(");
       render("PatternVariant");
       sh(_patternvariant.stellaident_);
       sh(_patternvariant.patterndata_);
       render(")");
    }
    if (foo instanceof stella.Absyn.PatternTuple)
    {
       stella.Absyn.PatternTuple _patterntuple = (stella.Absyn.PatternTuple) foo;
       render("(");
       render("PatternTuple");
       render("[");
       sh(_patterntuple.listpattern_);
       render("]");
       render(")");
    }
    if (foo instanceof stella.Absyn.PatternRecord)
    {
       stella.Absyn.PatternRecord _patternrecord = (stella.Absyn.PatternRecord) foo;
       render("(");
       render("PatternRecord");
       render("[");
       sh(_patternrecord.listlabelledpattern_);
       render("]");
       render(")");
    }
    if (foo instanceof stella.Absyn.PatternList)
    {
       stella.Absyn.PatternList _patternlist = (stella.Absyn.PatternList) foo;
       render("(");
       render("PatternList");
       render("[");
       sh(_patternlist.listpattern_);
       render("]");
       render(")");
    }
    if (foo instanceof stella.Absyn.PatternCons)
    {
       stella.Absyn.PatternCons _patterncons = (stella.Absyn.PatternCons) foo;
       render("(");
       render("PatternCons");
       sh(_patterncons.pattern_1);
       sh(_patterncons.pattern_2);
       render(")");
    }
    if (foo instanceof stella.Absyn.PatternFalse)
    {
       stella.Absyn.PatternFalse _patternfalse = (stella.Absyn.PatternFalse) foo;
       render("PatternFalse");
    }
    if (foo instanceof stella.Absyn.PatternTrue)
    {
       stella.Absyn.PatternTrue _patterntrue = (stella.Absyn.PatternTrue) foo;
       render("PatternTrue");
    }
    if (foo instanceof stella.Absyn.PatternInt)
    {
       stella.Absyn.PatternInt _patternint = (stella.Absyn.PatternInt) foo;
       render("(");
       render("PatternInt");
       sh(_patternint.integer_);
       render(")");
    }
    if (foo instanceof stella.Absyn.PatternSucc)
    {
       stella.Absyn.PatternSucc _patternsucc = (stella.Absyn.PatternSucc) foo;
       render("(");
       render("PatternSucc");
       sh(_patternsucc.pattern_);
       render(")");
    }
    if (foo instanceof stella.Absyn.PatternVar)
    {
       stella.Absyn.PatternVar _patternvar = (stella.Absyn.PatternVar) foo;
       render("(");
       render("PatternVar");
       sh(_patternvar.stellaident_);
       render(")");
    }
  }

  private static void sh(stella.Absyn.ListPattern foo)
  {
     for (java.util.Iterator<stella.Absyn.Pattern> it = foo.iterator(); it.hasNext();)
     {
       sh(it.next());
       if (it.hasNext())
         render(",");
     }
  }

  private static void sh(stella.Absyn.LabelledPattern foo)
  {
    if (foo instanceof stella.Absyn.ALabelledPattern)
    {
       stella.Absyn.ALabelledPattern _alabelledpattern = (stella.Absyn.ALabelledPattern) foo;
       render("(");
       render("ALabelledPattern");
       sh(_alabelledpattern.stellaident_);
       sh(_alabelledpattern.pattern_);
       render(")");
    }
  }

  private static void sh(stella.Absyn.ListLabelledPattern foo)
  {
     for (java.util.Iterator<stella.Absyn.LabelledPattern> it = foo.iterator(); it.hasNext();)
     {
       sh(it.next());
       if (it.hasNext())
         render(",");
     }
  }

  private static void sh(stella.Absyn.Binding foo)
  {
    if (foo instanceof stella.Absyn.ABinding)
    {
       stella.Absyn.ABinding _abinding = (stella.Absyn.ABinding) foo;
       render("(");
       render("ABinding");
       sh(_abinding.stellaident_);
       sh(_abinding.expr_);
       render(")");
    }
  }

  private static void sh(stella.Absyn.ListBinding foo)
  {
     for (java.util.Iterator<stella.Absyn.Binding> it = foo.iterator(); it.hasNext();)
     {
       sh(it.next());
       if (it.hasNext())
         render(",");
     }
  }

  private static void sh(stella.Absyn.Type foo)
  {
    if (foo instanceof stella.Absyn.TypeFun)
    {
       stella.Absyn.TypeFun _typefun = (stella.Absyn.TypeFun) foo;
       render("(");
       render("TypeFun");
       render("[");
       sh(_typefun.listtype_);
       render("]");
       sh(_typefun.type_);
       render(")");
    }
    if (foo instanceof stella.Absyn.TypeRec)
    {
       stella.Absyn.TypeRec _typerec = (stella.Absyn.TypeRec) foo;
       render("(");
       render("TypeRec");
       sh(_typerec.stellaident_);
       sh(_typerec.type_);
       render(")");
    }
    if (foo instanceof stella.Absyn.TypeSum)
    {
       stella.Absyn.TypeSum _typesum = (stella.Absyn.TypeSum) foo;
       render("(");
       render("TypeSum");
       sh(_typesum.type_1);
       sh(_typesum.type_2);
       render(")");
    }
    if (foo instanceof stella.Absyn.TypeTuple)
    {
       stella.Absyn.TypeTuple _typetuple = (stella.Absyn.TypeTuple) foo;
       render("(");
       render("TypeTuple");
       render("[");
       sh(_typetuple.listtype_);
       render("]");
       render(")");
    }
    if (foo instanceof stella.Absyn.TypeRecord)
    {
       stella.Absyn.TypeRecord _typerecord = (stella.Absyn.TypeRecord) foo;
       render("(");
       render("TypeRecord");
       render("[");
       sh(_typerecord.listrecordfieldtype_);
       render("]");
       render(")");
    }
    if (foo instanceof stella.Absyn.TypeVariant)
    {
       stella.Absyn.TypeVariant _typevariant = (stella.Absyn.TypeVariant) foo;
       render("(");
       render("TypeVariant");
       render("[");
       sh(_typevariant.listvariantfieldtype_);
       render("]");
       render(")");
    }
    if (foo instanceof stella.Absyn.TypeList)
    {
       stella.Absyn.TypeList _typelist = (stella.Absyn.TypeList) foo;
       render("(");
       render("TypeList");
       sh(_typelist.type_);
       render(")");
    }
    if (foo instanceof stella.Absyn.TypeBool)
    {
       stella.Absyn.TypeBool _typebool = (stella.Absyn.TypeBool) foo;
       render("TypeBool");
    }
    if (foo instanceof stella.Absyn.TypeNat)
    {
       stella.Absyn.TypeNat _typenat = (stella.Absyn.TypeNat) foo;
       render("TypeNat");
    }
    if (foo instanceof stella.Absyn.TypeUnit)
    {
       stella.Absyn.TypeUnit _typeunit = (stella.Absyn.TypeUnit) foo;
       render("TypeUnit");
    }
    if (foo instanceof stella.Absyn.TypeVar)
    {
       stella.Absyn.TypeVar _typevar = (stella.Absyn.TypeVar) foo;
       render("(");
       render("TypeVar");
       sh(_typevar.stellaident_);
       render(")");
    }
  }

  private static void sh(stella.Absyn.ListType foo)
  {
     for (java.util.Iterator<stella.Absyn.Type> it = foo.iterator(); it.hasNext();)
     {
       sh(it.next());
       if (it.hasNext())
         render(",");
     }
  }

  private static void sh(stella.Absyn.VariantFieldType foo)
  {
    if (foo instanceof stella.Absyn.AVariantFieldType)
    {
       stella.Absyn.AVariantFieldType _avariantfieldtype = (stella.Absyn.AVariantFieldType) foo;
       render("(");
       render("AVariantFieldType");
       sh(_avariantfieldtype.stellaident_);
       sh(_avariantfieldtype.optionaltyping_);
       render(")");
    }
  }

  private static void sh(stella.Absyn.ListVariantFieldType foo)
  {
     for (java.util.Iterator<stella.Absyn.VariantFieldType> it = foo.iterator(); it.hasNext();)
     {
       sh(it.next());
       if (it.hasNext())
         render(",");
     }
  }

  private static void sh(stella.Absyn.RecordFieldType foo)
  {
    if (foo instanceof stella.Absyn.ARecordFieldType)
    {
       stella.Absyn.ARecordFieldType _arecordfieldtype = (stella.Absyn.ARecordFieldType) foo;
       render("(");
       render("ARecordFieldType");
       sh(_arecordfieldtype.stellaident_);
       sh(_arecordfieldtype.type_);
       render(")");
    }
  }

  private static void sh(stella.Absyn.ListRecordFieldType foo)
  {
     for (java.util.Iterator<stella.Absyn.RecordFieldType> it = foo.iterator(); it.hasNext();)
     {
       sh(it.next());
       if (it.hasNext())
         render(",");
     }
  }

  private static void sh(stella.Absyn.Typing foo)
  {
    if (foo instanceof stella.Absyn.ATyping)
    {
       stella.Absyn.ATyping _atyping = (stella.Absyn.ATyping) foo;
       render("(");
       render("ATyping");
       sh(_atyping.expr_);
       sh(_atyping.type_);
       render(")");
    }
  }


  private static void pp(Integer n, int _i_) { buf_.append(n); buf_.append(" "); }
  private static void pp(Double d, int _i_) { buf_.append(String.format(java.util.Locale.ROOT, "%.15g ", d)); }
  private static void pp(String s, int _i_) { buf_.append(s); buf_.append(" "); }
  private static void pp(Character c, int _i_) { buf_.append("'" + c.toString() + "'"); buf_.append(" "); }
  private static void sh(Integer n) { render(n.toString()); }
  private static void sh(Double d) { render(String.format(java.util.Locale.ROOT, "%.15g", d)); }
  private static void sh(Character c) { render("'" + c.toString() + "'"); }
  private static void sh(String s) { printQuoted(s); }

  private static void printQuoted(String s) { render("\"" + s + "\""); }

  private static void indent()
  {
    int n = _n_;
    while (n > 0)
    {
      buf_.append(' ');
      n--;
    }
  }

  private static void backup()
  {
    int prev = buf_.length() - 1;
    if (prev >= 0 && buf_.charAt(prev) == ' ')
      buf_.setLength(prev);
  }

  private static void trim()
  {
    // Trim initial spaces
    int end = 0;
    int len = buf_.length();
    while (end < len && buf_.charAt(end) == ' ')
      end++;
    buf_.delete(0, end);
    // Trim trailing spaces
    removeTrailingSpaces();
  }

  private static void removeTrailingSpaces()
  {
    int end = buf_.length();
    while (end > 0 && buf_.charAt(end-1) == ' ')
      end--;
    buf_.setLength(end);
  }

  private static void removeTrailingWhitespace()
  {
    int end = buf_.length();
    while (end > 0 && (buf_.charAt(end-1) == ' ' || buf_.charAt(end-1) == '\n'))
      end--;
    buf_.setLength(end);
  }

  private static void onEmptyLine()
  {
    removeTrailingSpaces();
    int len = buf_.length();
    if (len > 0 && buf_.charAt(len-1) != '\n') buf_.append("\n");
    indent();
  }

  private static int _n_ = 0;
  private static StringBuilder buf_ = new StringBuilder(INITIAL_BUFFER_SIZE);
}

