(* File generated by the BNF Converter (bnfc 2.9.4.1). *)

type stellaIdent = StellaIdent of string
and extensionName = ExtensionName of string
and program =
   AProgram of languageDecl * extension list * decl list

and languageDecl =
   LanguageCore

and extension =
   AnExtension of extensionName list

and decl =
   DeclFun of annotation list * stellaIdent * paramDecl list * returnType * throwType * decl list * expr
 | DeclTypeAlias of stellaIdent * typeT

and localDecl =
   ALocalDecl of decl

and annotation =
   InlineAnnotation

and paramDecl =
   AParamDecl of stellaIdent * typeT

and returnType =
   NoReturnType
 | SomeReturnType of typeT

and throwType =
   NoThrowType
 | SomeThrowType of typeT list

and expr =
   If of expr * expr * expr
 | Let of stellaIdent * expr * expr
 | LessThan of expr * expr
 | LessThanOrEqual of expr * expr
 | GreaterThan of expr * expr
 | GreaterThanOrEqual of expr * expr
 | Equal of expr * expr
 | NotEqual of expr * expr
 | TypeAsc of expr * typeT
 | Abstraction of paramDecl list * expr
 | Tuple of expr list
 | Record of binding list
 | Variant of stellaIdent * exprData
 | Match of expr * matchCase list
 | List of expr list
 | Add of expr * expr
 | LogicOr of expr * expr
 | Multiply of expr * expr
 | LogicAnd of expr * expr
 | Application of expr * expr list
 | ConsList of expr * expr
 | Head of expr
 | IsEmpty of expr
 | Tail of expr
 | Succ of expr
 | LogicNot of expr
 | Pred of expr
 | IsZero of expr
 | Fix of expr
 | NatRec of expr * expr * expr
 | Fold of typeT * expr
 | Unfold of typeT * expr
 | DotRecord of expr * stellaIdent
 | DotTuple of expr * int
 | ConstTrue
 | ConstFalse
 | ConstInt of int
 | Var of stellaIdent

and matchCase =
   AMatchCase of pattern * expr

and optionalTyping =
   NoTyping
 | SomeTyping of typeT

and patternData =
   NoPatternData
 | SomePatternData of pattern

and exprData =
   NoExprData
 | SomeExprData of expr

and pattern =
   PatternVariant of stellaIdent * patternData
 | PatternTuple of pattern list
 | PatternRecord of labelledPattern list
 | PatternList of pattern list
 | PatternCons of pattern * pattern
 | PatternFalse
 | PatternTrue
 | PatternInt of int
 | PatternSucc of pattern
 | PatternVar of stellaIdent

and labelledPattern =
   ALabelledPattern of stellaIdent * pattern

and binding =
   ABinding of stellaIdent * expr

and typeT =
   TypeFun of typeT list * typeT
 | TypeRec of stellaIdent * typeT
 | TypeSum of typeT * typeT
 | TypeTuple of typeT list
 | TypeRecord of recordFieldType list
 | TypeVariant of variantFieldType list
 | TypeList of typeT
 | TypeBool
 | TypeNat
 | TypeUnit
 | TypeVar of stellaIdent

and variantFieldType =
   AVariantFieldType of stellaIdent * optionalTyping

and recordFieldType =
   ARecordFieldType of stellaIdent * typeT

and typing =
   ATyping of expr * typeT

