// File generated by the BNF Converter (bnfc 2.9.4.1).

package stella.Absyn;

public abstract class Decl implements java.io.Serializable {
  public abstract <R,A> R accept(Decl.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(stella.Absyn.DeclFun p, A arg);
    public R visit(stella.Absyn.DeclTypeAlias p, A arg);

  }

}
