// File generated by the BNF Converter (bnfc 2.9.4.1).

package stella.Absyn;

public abstract class LabelledPattern implements java.io.Serializable {
  public abstract <R,A> R accept(LabelledPattern.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(stella.Absyn.ALabelledPattern p, A arg);

  }

}
