// File generated by the BNF Converter (bnfc 2.9.4.1).

package stella.Absyn;

public abstract class OptionalTyping implements java.io.Serializable {
  public abstract <R,A> R accept(OptionalTyping.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(stella.Absyn.NoTyping p, A arg);
    public R visit(stella.Absyn.SomeTyping p, A arg);

  }

}
