// File generated by the BNF Converter (bnfc 2.9.4.1).

package stella.Absyn;

public abstract class Pattern implements java.io.Serializable {
  public abstract <R,A> R accept(Pattern.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(stella.Absyn.PatternVariant p, A arg);
    public R visit(stella.Absyn.PatternTuple p, A arg);
    public R visit(stella.Absyn.PatternRecord p, A arg);
    public R visit(stella.Absyn.PatternList p, A arg);
    public R visit(stella.Absyn.PatternCons p, A arg);
    public R visit(stella.Absyn.PatternFalse p, A arg);
    public R visit(stella.Absyn.PatternTrue p, A arg);
    public R visit(stella.Absyn.PatternInt p, A arg);
    public R visit(stella.Absyn.PatternSucc p, A arg);
    public R visit(stella.Absyn.PatternVar p, A arg);

  }

}
