// File generated by the BNF Converter (bnfc 2.9.4.1).

package stella.Absyn;

public abstract class ReturnType implements java.io.Serializable {
  public abstract <R,A> R accept(ReturnType.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(stella.Absyn.NoReturnType p, A arg);
    public R visit(stella.Absyn.SomeReturnType p, A arg);

  }

}
