// File generated by the BNF Converter (bnfc 2.9.4.1).

package stella.Absyn;

public class SomeExprData  extends ExprData {
  public final Expr expr_;
  public int line_num, col_num, offset;
  public SomeExprData(Expr p1) { expr_ = p1; }

  public <R,A> R accept(stella.Absyn.ExprData.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof stella.Absyn.SomeExprData) {
      stella.Absyn.SomeExprData x = (stella.Absyn.SomeExprData)o;
      return this.expr_.equals(x.expr_);
    }
    return false;
  }

  public int hashCode() {
    return this.expr_.hashCode();
  }


}
