// File generated by the BNF Converter (bnfc 2.9.4.1).

package stella.Absyn;

public abstract class ThrowType implements java.io.Serializable {
  public abstract <R,A> R accept(ThrowType.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(stella.Absyn.NoThrowType p, A arg);
    public R visit(stella.Absyn.SomeThrowType p, A arg);

  }

}
